### ISSUE TITLE
Same public_id gets assigned to many images on multiple uploads

### ISSUE THREAD

**Issue by theodorton** [cloudinary/cloudinary_js#10]
I'm trying to do multiple uploads to the Cloudinary API, but they all seem to get the same public_id.

I uploaded 8 images and in my Chrome Developer Console I see 9 requests in my Network tab (1 `head` and 8 `post` requests).

All the `post` requests look the same to me (except for the file field). The signature, timestamp and public api key are the same.

The response for 7 out of the 8 `post` requests are also identical. 7 of the images get the same public id (`amgfphycgixuuihodxg9`) and the last one gets a unique one `b4yhpxzizprgokm3xivy`.

This is my HTML for the upload images-button:

``` html
<input
  accept="image/jpeg,image/png"
  class="cloudinary-fileupload"
  data-cloudinary-field="image_management_batch_upload[image_ids]"
  data-form-data="{ ... }"
  data-url="https://api.cloudinary.com/v1_1/skalar-tt/auto/upload"
  multiple="multiple"
  name="file"
  type="file">
```

I'm not using any custom js.

**Comment by matthieu80** [comment]
Still a problem with this with Rails:
<%= cl_image_upload_tag(:image_id, :html => {:class => "image_upload", :multiple => true}) %>

I can see the first upload applied to the form, but I cannot add more than one. Do I have to change the first param to an array? ("image_id")
