### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by NitroBAY** [cloudinary/cloudinary_js#101]
Other SDK than JS/jQuery can generate responisves images http://cloudinary.com/blog/how_to_automatically_create_images_for_responsive_design#api_example_1
But if I try with the JS library : 
```
myCloudinary.image('v0c05biaesv6huoq4ayl', { width: 'auto', 'dpr': 'auto', responsive_placeholder: "blank" })​
```
it returns 
`<img src=​"http:​/​/​res.cloudinary.com/​****/​image/​upload/​dpr_2.0/​v0c05biaesv6huoq4ayl">`
And in any way whatever I do width: 'auto' should add w_auto to the URL, like upload/w_auto but width: 'auto' never create w_auto.
Besides if I create an img with data-src, w_auto (I modifiy  by myself with a DOM explorer) and a class cld-responsive `myCloudinary.responsive()` does not create a proper image...
Is there a specific reason of such differences between this SDK and the other ?

**Comment by tocker** [comment]
You must add a `crop` parameter to the transformation when using the width parameter.

```
myCloudinary.image('v0c05biaesv6huoq4ayl', { width: 'auto', crop: 'scale', dpr: 'auto', responsive_placeholder: "blank" })
```

(The documentation link you mention does not include a JavaScript example. We are aware of it and working on improving the documentation for the javascript libraries.)

**Comment by NitroBAY** [comment]
Okay but shouldn't work on having the same behaviour as with other SDK ? And Yeah the fact that there is specific behavior just with this library and that it's not documentated make it really hard to guess.

**Comment by NitroBAY** [comment]
PS : I still need help on #99 @tocker

**Comment by NitroBAY** [comment]
I'm disappointed that there's no answer to why is there such discrepancies between js version and other and to the fact that JS version has an huge lack of documentation.

**Comment by taragano** [comment]
Hi @NitroBAY,

I apologize for our response delay.

AFAIK, all our SDKs are actually consistent about this matter, in other words, the `crop` parameter is obligatory on all SDKs when generating transformed URLs.
Regardless, thank you for your feedback, and we'll do our best to make this clearer in our docs.
