### ISSUE TITLE
fileuploadprogress

### ISSUE THREAD

**Issue by NitroBAY** [cloudinary/cloudinary_js#103]
Hello,
`  $('#upload-img').unsigned_cloudinary_upload('secretuploadpreset', { cloud_name })
  .on('fileuploadprogress', (e, data) => {
    console.log(Math.round((data.loaded * 100.0) / data.total));
  })`

Upload is working but when I want to make a progress bar but the above code only log `100 `so it's pointless.

**Comment by taragano** [comment]
Hi @NitroBAY,

Have you tried this with larger images? For smaller ones it may indeed directly update when on 100%.

**Comment by NitroBAY** [comment]
I tried with a 4k image. Previously it was working on every images. I will try with a throttled connection

**Comment by taragano** [comment]
Thank you, regardless, we're doing some further checks on our end, just to make sure.

**Comment by eitanp461** [comment]
@NitroBAY I created a sample project in JSFiddle where upload events are functioning as expected  - https://jsfiddle.net/eitanp461/c3hvp3by/

Can you add more details regarding your setup? Which versions of Cloudinary and jQuery are you using? Are you using jQuery at all?

It would be great if you could reproduce the issue based on the provided fiddle.

Thanks,
Eitan
