### ISSUE TITLE
broken dependency `blueimp-file-upload` when using bower/amd

### ISSUE THREAD

**Issue by bestrada** [cloudinary/cloudinary_js#104]
https://github.com/cloudinary/cloudinary_js/blob/6a8f2dbf6463ac00892e9e13679935ec3b76a59c/bower.json#L48

this dependency made some breaking changes in `9.12.6` which was released 10/17/2016. the jquery-ui folks updated the AMD module naming convention, but it looks like your library has hard-coded against the old naming convention.

https://github.com/blueimp/jQuery-File-Upload/commit/a9bfde1cfe7c5295b3757a28fbffe06087701749

you should either change the dependency to be max `9.12.5` or otherwise somehow fix this dependency.

**Comment by tocker** [comment]
Hi @bestrada,

Thanks for catching this!
We will change our sources to reflect this change.

Please note that while the dependency has changed in Blueimp, there are a few issues to consider:

1. The recommendation on the [jQuery documentation](https://learn.jquery.com/jquery-ui/environments/amd/) that led to the change requires a _particular file structure_ that may not conform to all websites. Specifically, it differs greatly from the bower installation.
2. The `cloudinary_js` is the source repository for the Cloudinary JavaScript libraries. You should use the distribution pakcage [`cloudinary-jquery-file-upload`](https://bower.io/search/?q=cloudinary-jquery-file-upload) instead. In that library we removed the `jquery-ui` dependency.
3. The Blueimp distribution includes the jQuery UI widget, so you can include it directly without installing the full jQuery UI library.

When using **bower** or **npm** as a package manager we recommend configuring requirejs rather then moving the sources to a new folder structure. See our [test file](https://github.com/cloudinary/cloudinary_js/blob/6a8f2dbf6463ac00892e9e13679935ec3b76a59c/test/docRoot/amd.html#L23-L32) as an example:

```javascript
requirejs.config({
    baseUrl: 'bower_components',
    paths: {
        'jquery': 'jquery/dist/jquery.min',
        'jquery-ui/widget': 'blueimp-file-upload/js/vendor/jquery.ui.widget',
        'jquery.iframe-transport': 'blueimp-file-upload/js/jquery.iframe-transport',
        'jquery.fileupload': 'blueimp-file-upload/js/jquery.fileupload'
    }
});
```
(Notice that the `jquery-ui/widget` entry above is not included yet in our source and will be fixed.)

If you prefer to use the widget from jquery-ui bower distribution, modify the above configuration to include:

```javascript
  'jquery-ui/widget': 'jquery-ui/ui/widget'
```
