### ISSUE TITLE
Sign request on server, direct upload on browser, without client library

### ISSUE THREAD

**Issue by bkniffler** [cloudinary/cloudinary_js#106]
Hi, 
I'd like to use cloudinary without your client side library. With nodejs `cloudinary.utils.sign_request` I can get a signature, but now what? How do I need to design my post request? What url do I need to target my post request to?

**Comment by Haocen** [comment]
Would be happy to know how as well.

**Comment by taragano** [comment]
@Haocen,

This was also discussed on a different thread:
https://github.com/cloudinary/cloudinary_js/issues/81

If you run into some specific issues, please feel free to [open a support ticket](https://support.cloudinary.com/hc/en-us/requests/new), share some context of the code you're using, and we'll be happy to assist.

**Comment by Haocen** [comment]
@taragano That should be in your official documentation, much more comprehensive.

**Comment by bkniffler** [comment]
Yeah, I managed to do it and failed to update this question accordingly. So again, for signed uploads: 

First I calculate the signature on server side using
```
cloudinary.utils.sign_request({ timestamp: Math.round(new Date().getTime()/1000) });
// returns { signature, api_key, timestamp }
```

On the browser, I call this method through my API and attach the properties as fields like here (with superagent)

```
const request = superagent
        .post("https://api.cloudinary.com/v1_1/<cloud name>/auto/upload")
        .on('progress', ({ percent }) => console.log(`${percent}%`))
        .field('api_key', data.api_key)
        .field('signature', data.signature)
        .field('timestamp', data.timestamp);
```
And done!

**Comment by bkniffler** [comment]
Btw. I agree this could be made more clear in the docs.

**Comment by taragano** [comment]
@Haocen @bkniffler,
Thank you both for your feedback. We'll definitely do our best to make this clearer in our docs.
