### ISSUE TITLE
$.extend() does not with with noconflict

### ISSUE THREAD

**Issue by hrtrulz** [cloudinary/cloudinary_js#109]
I am using jQuery in noconflict mode and I was getting a error when trying to the fileuploader. 

on Line 3937 `data.headers = $.extend({}, data.headers, {` where the error was occurring. I changed it to `data.headers = jQuery.extend({}, data.headers, {` and it works

**Comment by taragano** [comment]
I'm sorry for my response delay @hrtrulz.

Can you please make sure you're using the latest version of our library? It seems that [line 3937](https://github.com/cloudinary/cloudinary_js/blob/5019331948e51e307a7e69c777f3868e3ba01825/js/jquery.cloudinary.js#L3937) is different than what the code line you referred to (changed in 2.1.3 last September).

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
