### ISSUE TITLE
The "delay" transformation gets incorrectly translated in the URL as "l" instead of "dl"

### ISSUE THREAD

**Issue by gvillenave** [cloudinary/cloudinary_js#111]
Using a "delay" transformation on a video (when generating an animated GIF) results in an invalid Cloudinary URL because it gets added as "l" instead of "dl". I submitted #110 with a fix.

**Comment by taragano** [comment]
Thank you for reporting about this @gvillenave,
Our team will take care of this.

**Comment by tocker** [comment]
Thanks for the pull request!
Merged #110 .

**Comment by gvillenave** [comment]
@tocker Can you also update the distribution repos with this fix? https://github.com/cloudinary/pkg-cloudinary-jquery and https://github.com/cloudinary/pkg-cloudinary-jquery-file-upload

**Comment by gvillenave** [comment]
Ping! Any update on updating the distribution repos? The bower package is still behind without this fix. Thanks!
