### ISSUE TITLE
Chaining issue with width()

### ISSUE THREAD

**Issue by d3v1an7** [cloudinary/cloudinary_js#115]
It looks like if there are 2 instances of `width()` in a chained transform, the second one is lost. This does not seem to be an issue with other attributes (very minimal testing).

Version: `https://cdnjs.cloudflare.com/ajax/libs/cloudinary-core/2.1.9/cloudinary-core-shrinkwrap.min.js`

**From README.md example:**
```
var tr = cloudinary.Transformation.new();
tr.width(10).crop('fit').chain().angle(15).serialize();
// "c_fit,w_10/a_15" <-- correct!
```

**Switching `.angle(15)` after `chain()` to `.width(15)`**
```
var tr = cloudinary.Transformation.new();
tr.width(10).crop('fit').chain().width(15).serialize();
// "c_fit,w_10" <-- width(15) declaration lost :(
```

**`angle()` seems to be okay though?**
```
var tr = cloudinary.Transformation.new();
tr.angle(10).crop('fit').chain().angle(15).serialize();
// "a_10,c_fit/a_15" <-- correct!
```

Interestingly, when outputting the image tag, the lost `width(15)` seems to have been converted to an `<img>` tag attribute:
```
<img src="[...]/image/upload/c_fit,w_10/image.jpg" width="15">
```

**Comment by taragano** [comment]
Unlike the dynamic URLs, using our SDK requires including a `crop` mode when using `width`.
The following works:

```
var tr = cloudinary.Transformation.new();
tr.width(10).crop('fit').chain().width(15).crop("scale").serialize();
// "c_fit,w_10/c_scale,w_15"  <-- correct!
```

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
