### ISSUE TITLE
Incomplete release of cloudinary-jquery-file-upload

### ISSUE THREAD

**Issue by holtkamp** [cloudinary/cloudinary_js#123]
When updating our dependencies, `cloudinary-jquery-file-upload` version `2.2.1` is fetched. However, loading it from CDNJS fails:

- 2.2.0 works: https://cdnjs.cloudflare.com/ajax/libs/cloudinary-jquery-file-upload/2.2.0/cloudinary-jquery-file-upload.js
- 2.2.1 fails: https://cdnjs.cloudflare.com/ajax/libs/cloudinary-jquery-file-upload/2.2.1/cloudinary-jquery-file-upload.js

It seems `2.2.1` was tagged, but not released?

https://github.com/cloudinary/pkg-cloudinary-jquery-file-upload/releases

![screen shot 2017-03-17 at 11 44 58](https://cloud.githubusercontent.com/assets/776405/24040030/92f1c826-0b07-11e7-95ec-82875ed87a59.png)

**Comment by tocker** [comment]
@holtkamp thanks for catching this!
Fixed.

**Comment by holtkamp** [comment]
@tocker mmm, for some reason [CDNJS still does not detect](https://cdnjs.com/libraries/cloudinary-jquery-file-upload) this `2.2.1`, 

Seems like the NPM repository is not updated as well:

https://www.npmjs.com/package/cloudinary-jquery-file-upload

Should this work automatically? Or is a manual trigger required?

**Comment by tocker** [comment]
@holtkamp - fixed.
NPM has been updated. CDNJS will probably pick it up in the next refresh.

**Comment by holtkamp** [comment]
Great, all in-sync now:

https://cdnjs.cloudflare.com/ajax/libs/cloudinary-jquery-file-upload/2.2.1/cloudinary-jquery-file-upload.js
