### ISSUE TITLE
Configuring UI

### ISSUE THREAD

**Issue by joergd** [cloudinary/cloudinary_js#124]
Hi - I can't see documentation anywhere to change the UI for the jquery upload button and text. Is this possible?

**Comment by idobarnoam** [comment]
Hi
Are you referring to the upload widget button?
If do you can find it in the link below:
http://cloudinary.com/documentation/upload_widget#look_feel_customization

**Comment by idobarnoam** [comment]
Hi @joergd  Closing this issue due to the time elapsed. 

Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

Thanks
