### ISSUE TITLE
Listening on Cloudinary Responsive Events

### ISSUE THREAD

**Issue by akshat12** [cloudinary/cloudinary_js#125]
1. I was wondering if there were some events triggered when the `img` src is set or changed when using `cloudinary.responsive()`?
2. If any such events exist, which ones should I be listening to?

**Comment by strausr** [comment]
@akshat12 We don't have an event fired for changing responsive images.

Could you please elaborate on your functional use case?

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
