### ISSUE TITLE
support for react native ? 

### ISSUE THREAD

**Issue by kaiyes** [cloudinary/cloudinary_js#130]
Hi, 
Is there any support for react native ? I have been using cloudinary for the past two years with meteor so would hate to change now. 
There is this over complicated https://www.npmjs.com/package/react-native-cloudinary package but I am looking for something easier/Official. 

Thanks in Advance ! 😄

**Comment by strausr** [comment]
Hi @kaiyes, 
It is on our roadmap to add support for react native though no ETA at the moment. We'd be happy to ping once this is added to our roadmap.
