### ISSUE TITLE
Jquery free upload example

### ISSUE THREAD

**Issue by kaihendry** [cloudinary/cloudinary_js#132]
I am looking for a sane jquery free upload example that can ideally have multiple uploads.

Icing on the cake would be somehow showing how to isolate uploads between users and build up a gallery for a particular user.

**Comment by eitanp461** [comment]
@kaihendry check out https://codepen.io/eitanp461/pen/GrRWma
It's an example of using jQuery's blueimp plugin.

Assuming you have a way to identify users, you can add custom tags per user to create per-user galleries, see https://cloudinary.com/documentation/admin_api#list_resources_by_tag

**Comment by kaihendry** [comment]
On Sun, 15 Oct 2017, at 05:49 PM, Eitan Peer wrote:
> Assuming you have a way to identify users, you can add custom tags per
> user to create per-user galleries, see
> https://cloudinary.com/documentation/admin_api#list_resources_by_tag

I'm surprised you are recommending tags. We are familiar with prefixing
tenants and querying like that.


Here is a Jquery free example I found via twitter
https://twitter.com/cloudinary/status/918894828418613249

**Comment by eitanp461** [comment]
@kaihendry prefixing and tags are different solutions for creating custom galleries.

Note that prefixes are part of the resource id, and also serve as part of the CDN cache key.
By using tags you can dynamically update the resource without creating a new version.
I suppose that it is less important when creating user galleries based on unique user names.

BTW, I got confused by the question, and provided a jQuery example, obviously the example you got on Twitter better suits your needs.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
