### ISSUE TITLE
Unsupported source URL 

### ISSUE THREAD

**Issue by sagomezza** [cloudinary/cloudinary_js#143]
Hi, 

I'm developing an React Native app with Expo, I'm trying to upload an image by diverse methods suggested in this issue:  
[https://github.com/cloudinary/cloudinary_js/issues/93](url)
None of them gave me feedback about the problem (I was getting response 400), but actually the fetch method did. I'm getting Unsupported source URL when I'm passing the FileDirectory path of the image. 

I don't know if maybe this has to do with this:
[https://github.com/cloudinary/cloudinary_js/issues/130](url)

Code: 

uploadToCloudinary(id) {
  const uri =  FileSystem.documentDirectory + 'photos/Photo_' + id + '.jpg';
  const url = "https://api.cloudinary.com/v1_1/aaaaaaaaa/image/upload/";
  const formData = new FormData();
  formData.append("file", uri);
  formData.append("tags", `vehicle`);
  formData.append("upload_preset", "aaaaaa"); 
  formData.append("api_key", "1234567890"); 
  fetch(url, {
    method: 'POST',
    body: formData
  })
  .then(response => {
    console.log(response)
    var reader = response.body.getReader();
    var decoder = new TextDecoder();
    var decodedValue;
    function update() {
      return reader.read().then(function(result) {
        if (result.done) {
          console.log(JSON.parse(decodedValue))
          return (JSON.parse(decodedValue));
        }
        decodedValue = decoder.decode(result.value || new Uint8Array, {
          stream: true
        });
        console.log(decodedValue)
        return update();      
      });
    }
    return update();
  });
}

Update: Now I tried a live example in pure JS. So it seems the file object us more complex than I thought. So, do I have to wait for a RN support or there is any workaround to this?. 
Also I forgot to mention that I can't use an ImagePicker, because the image is a photo taken by the user.

**Comment by paddy57** [comment]
@sagomezza did you find any solution to this ?

**Comment by mdnmnahmed** [comment]
i also getting the same error...
did you fix it?

**Comment by shirlymanor** [comment]
Can you try the following code sample and let us know if that works?
https://codesandbox.io/embed/jq4wl1xjv

**Comment by arghac14** [comment]
const data = new FormData()
        data.append("file",image)
        data.append("upload_preset","blogfeed")
        data.append("cloud_name","<cloud_name>")
        console.log(data)
        fetch("https://api.cloudinary.com/v1_1/<cloud_name>/image/upload",{
            method:"post",
            body:data
        })
        .then(res=>res.json())
        .then(data=>{
            console.log(data)
        })
        .catch(err=>{
            console.log(err)
        })


Can anyone solve the issue , I'm getting-

AddPost.js:16 POST https://api.cloudinary.com/v1_1/arghac14/image/upload 400 (Bad Request)
AddPost.js:22 
{error: {…}}
error: {message: "Unsupported source URL: [object FileList]"}
__proto__: Object

@shirlymanor  @sagomezza  @mdnmnahmed  @paddy57

**Comment by shirlymanor** [comment]
@arghac14 I've shared with you the code sample (to your email). please let us know if that works.

**Comment by arghac14** [comment]
@shirlymanor I have used your code snippet but still getting the same error, please look-


![Capture1](https://user-images.githubusercontent.com/38630062/89211901-277b3d00-d5e0-11ea-935a-0295cb797666.PNG)
![Capture](https://user-images.githubusercontent.com/38630062/89211908-2c3ff100-d5e0-11ea-9ba9-3bd92ef4007f.PNG)


function AddPost() {
    const [title, setTitle] = useState("")
    const [tag, setTag] = useState("")
    const [body, setBody] = useState("")
    const [image, setImage] = useState("")

    const addPost = async ()=>{
        //console.log(image)
        var formdata = new FormData();

        formdata.append("file", image);
        formdata.append("cloud_name", "arghac14");
        formdata.append("upload_preset", "blogfeed");

        let res = await fetch(
        "https://api.cloudinary.com/v1_1/arghac14/auto/upload",
        {
            method: "post",
            mode: "cors",
            body: formdata
        }
        )
        .then(res=>res.json())
        .then(data=>{
            console.log(data)
        })
        .catch(err=>{
            console.log(err)
        })
    }

**Comment by shirlymanor** [comment]
Can you please share the file that you are trying to upload?
Might be easier if you can open a ticket at support@cloudinary.com

**Comment by arghac14** [comment]
@shirlymanor the issue is solved now. My bad, I didn't use e.target.files[0] before. Thanks for your help!

**Comment by shirlymanor** [comment]
@arghac14 thanks for the update!

**Comment by FeezyHendrix** [comment]
Any solution for react native?

**Comment by leptians** [comment]
Hi @FeezyHendrix, since this is a long old thread, to make sure I got the right context of what you are looking for, can you share more details of what you are trying to achieve? I recommend to open a support ticket from our [portal](https://support.cloudinary.com/hc/en-us/requests/new) with the details.

**Comment by diaaatya** [comment]
will  it work for me when I add an object first with the name and the type of the image along with the image URI then pass this file to the FormData that will be uploaded to Cloudinary   

const imageUpload = (image) =>{
    let newfile ={
        uri  : image,
        type : "test/jpg",
        name : "test-unoqe-name12"
    }
    const data = new FormData()
    data.append('file',newfile)
    data.append('upload_preset','diaamond')
    data.append('cloud_name','diaamondsoft')
    fetch("https://api.cloudinary.com/v1_1/diaamondsoft/image/upload",{
      method:"post",
      body:data
    }).then(res=>res.json())
    .then(data =>{
      console.log(data)
    })
  }

**Comment by igy** [comment]
Hi Diaaatya,

This thread was about how to send the `file` parameter correctly when calling our API directly. The `file` parameter of the upload API must be the actual file bytes, a base64 encoded data URI, or a remote URI from which we can retrieve the image.

In your example code, it looks like you're passing a JSON object as the 'file' parameter which will not work. The possible options for the file parameter can be found here: https://cloudinary.com/documentation/image_upload_api_reference#required_parameters

Your code may work if you change `data.append('file',newfile)` to `data.append('file',newfile.image)`, assuming that the URL in `image` is accessible to us when we try to retrieve it. 
If you're still not able to get it to work, please contact us directly via https//support.cloudinary.com ("Submit a request" link on the top) and include the details of the call and response including all parameters and we'll check it for you

Thanks,
Stephen
