### ISSUE TITLE
Unreleased cloudinary-jquery-file-upload changes

### ISSUE THREAD

**Issue by skeggse** [cloudinary/cloudinary_js#145]
Hey @tocker - it looks like https://github.com/cloudinary/pkg-cloudinary-jquery-file-upload/commit/eb076a47759444981618634828d43d4e33a106fc isn't included in the latest npm release of `cloudinary-jquery-file-upload` - can you release a new version?

**Comment by yakirp** [comment]
Hi @skeggse , we hope to release it next week, sorry for the inconvenience.

**Comment by skeggse** [comment]
Not to be a pain, but do you have an updated ETA?

**Comment by yakirp** [comment]
Hi, 

This issue has been fixed and release:
https://github.com/cloudinary/cloudinary_ios/releases

Cheers,
Yakir

**Comment by yakirp** [comment]
I'm sorry this issue still does not fix. I will update you.

**Comment by tocker** [comment]
Fixed in version 2.6.0
