### ISSUE TITLE
Destroying Media

### ISSUE THREAD

**Issue by reinhardholl** [cloudinary/cloudinary_js#146]
Hi,

I am trying to remove videos from my library using the JS package. I am calling the following command:

```
cloudinary.v2.uploader.destroy(name, {
            invalidate: true,
        }, (result) => {
            console.log(result);
        });
```

`result` in this case is always `undefined`,  and the media does not get removed. What am I doing wrong?

Thanks!

**Comment by strausr** [comment]
Can you share with us your cloudname and the public id of the resource you're trying to remove? You can also open a ticket at support@cloudinary.com with this information.

**Comment by reinhardholl** [comment]
Hey, its `dzoyfppkz` and resource name is `10.mp4`

**Comment by strausr** [comment]
Looking into our logs, I can see that the resource was successfully deleted and then re-uploaded. Can you please check that you're not re-uploading it post deletion? 

Also, you're console logging the error rather than the result. For example-

```
cloudinary.v2.uploader.destroy(name, {
            invalidate: true,
        }, (err, result) => {
            console.log(result);
        });  
```

**Comment by reinhardholl** [comment]
Interesting, thanks for the info. Pretty sure we are not re-uploading it. Let me just check my logs to make sure.

**Comment by reinhardholl** [comment]
Hey @strausr 

After reading the correct param in the callback (`result` vs `err`) I see get `{ result: 'not found' }` (Should this not be an error?)

Anyway, definitely not re-uploading the file.

**Comment by strausr** [comment]
Since you're deleting a video, can you please add resource_type:'video' and make sure that when you're supplying the name it is the public_id without the extension? 


```
 cloudinary.v2.uploader.destroy('10', {
            resource_type:'video', invalidate: true,
        }, (err, result) => {
            console.log(err, result);
        });
```

**Comment by reinhardholl** [comment]
Thanks @strausr. It was indeed the `resource_type:'video'` that was missing. It makes 100% sense thinking about it now, might be a good idea to add this to the docs 👍

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
