### ISSUE TITLE
Is there a way on the client side to generate video thumbnail( poster) from a given video url ?  (The video was uploaded to cloudinary)

### ISSUE THREAD

**Issue by changliu86** [cloudinary/cloudinary_js#150]
I was looking for a way to display a video poster from given video url.  I looked into the "Generating video thumbnails" methods at https://cloudinary.com/documentation/video_manipulation_and_delivery#generating_video_thumbnails.  But unfortunately, none of them works. Can someone show me how ? 

A simple example of how I get the video url from a givien public id : 
getVideoUrl(videoId){
     return window.cl.video_url(videoId, {
          height: '0.5',
          width: '1.0',
          crop: 'fill',
        });
}

 "cloudinary-core": "^2.5.0",
 "vue": "^2.5.2",

Thanks !

**Comment by igy** [comment]
Hi,

In general, you can simply request a video thumbnail by asking us to return the video, but then changing the file extension to .jpg, .png, etc.

In the Cloudinary JS SDK, there's also a helper method similar to the `cl.video_url` function in your example.
This is the `video_thumbnail_url()` function. You can find its definition in the code here: https://github.com/cloudinary/cloudinary_js/blob/2.5.0/src/cloudinary.coffee#L217

Using your code as a starting point, you should be able to do something like this:
 ```
getVideoThumbnailUrl(videoId){
return window.cl.video_thumbnail_url(videoId, {
height: '0.5',
width: '1.0',
crop: 'fill',
});
}
```

Please try that, and let me know if it works for you.

**Comment by changliu86** [comment]
It works out of box and 100% solve my problem.  Thank you very much !

**Comment by igy** [comment]
You're welcome; glad you were able to get it working!
