### ISSUE TITLE
Cloudinary player errors after latest update

### ISSUE THREAD

**Issue by adzhazhev** [cloudinary/cloudinary_js#151]
Hello, I've been using the Cloudinary service for a few months and I found that after the latest updates to the core library(which is a dependency to the https://github.com/cloudinary/cloudinary-video-player) now there's an issue.

If you are loading the player files from the cdn like this:

```
<script src="https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js" type="text/javascript"></script>
<script src="https://unpkg.com/cloudinary-video-player/dist/cld-video-player.min.js"
        type="text/javascript"></script>
```

You get the following error:
```
Uncaught TypeError: Cannot set property 'VideoPlayer' of undefined
    at Object.<anonymous> (cld-video-player.min.js:1)
    at i (cld-video-player.min.js:1)
    at cld-video-player.min.js:1
    at cld-video-player.min.js:1
    at webpackUniversalModuleDefinition (cld-video-player.min.js:1)
    at cld-video-player.min.js:1
```

I might be wrong, but my implementation was working until the latest commits on this repository and since I haven't changed anything this is the conclusion I came to. I'm sorry if I am making a false alert 🗡  Please take a look.

**Comment by aditimadan-Cloudinary** [comment]
We had some issues with the video player which have been fixed now. Please test and let us know if you still see any problem.

**Comment by adzhazhev** [comment]
It's all good now, thanks.
