### ISSUE TITLE
disable widget minimize

### ISSUE THREAD

**Issue by mikestaub** [cloudinary/cloudinary_js#160]
Is there a repo to add issues for the upload widget?

I have a 2 feature requests: 

1) add an option to allow disabling of the widget minimize feature ( disableMinimize )
2) add an option to force the user to crop the image ( forceCrop )

**Comment by yakirp** [comment]
Hi @mikestaub 

About 1 - I need to check with the team.
about 2 - It's on our roadmap.

I will update.

Best

**Comment by yakirp** [comment]
Hi, 

About 1- I created a feature request on your behalf. Will keep you posted.

Best

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by mikestaub** [comment]
@roeeba can you leave it open until @yakirp confirms the feature is shipped?

**Comment by shirlymanor** [comment]
sure, we reopen it. @yakirp

**Comment by yakirp** [comment]
Hey @mikestaub ,
Force cropping is now available, please see the `showSkipCropButton` option. 
https://cloudinary.com/documentation/upload_widget

Please let me know if it works for you. 

Regarding the minimize- still on our roadmap. 

Thanks, 
Yakir

**Comment by yakirp** [comment]
Since this issue is not related to our js SDK, I will close this one but will update here in the futre. Thanks
