### ISSUE TITLE
No Version in URL

### ISSUE THREAD

**Issue by GaddMaster** [cloudinary/cloudinary_js#188]
I not sure if I should be putting this here but seems the best place.

My images have no version (timestamp) in the URL when received by component, but my images URL on cloudinary have them.

I can't find any docs for <Image/> to see if there is a param for it

Any help?

Daniel

**Comment by shirlymanor** [comment]
Hi Daniel,

Also answered on the ticket :)
When creating the URL in the UI we can't create the version. It will work without the version.
The only thing is if you need to update an already uploaded image. If you are planing that. we recommend contact support and we configure your account to invalidate un-versioned URL.
