### ISSUE TITLE
Typescript definition is not updated

### ISSUE THREAD

**Issue by love2dishtech** [cloudinary/cloudinary_js#189]
I am trying to use a feature of the library which I figured out after looking at the code which is to use the source set and the picture tag feature. I couldn't find any documentation for the same either, but i see it works.

However, I see that the typescript definition does not have either of these  methods which is the sourceTag() and pictureTag() to directly construct HTML nodes as the imageTag(). However, I see there are PictureTag classes and SourceTag classes both in the TS definitions.

Update: Definition of PictureTag is also not updated.

**Comment by eitanp461** [comment]
@love2dishtech thank you for bringing this issue to our attention. I will ask the relevant dev team to update it.

**Comment by eyalktCloudinary** [comment]
@love2dishtech Hey, can you please elaborate on your use-case with the sourceTag() function?
Thanks!

**Comment by eyalktCloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or contact our support at http://support.cloudinary.com.
