### ISSUE TITLE
Picture Tag Helper function does not work.

### ISSUE THREAD

**Issue by love2dishtech** [cloudinary/cloudinary_js#190]
## Issue and Reproduction steps
The following piece of code breaks when trying to use the picture tag feature of cloudinary js core component.

```javascript
 const cl:any = new Cloudinary({
    "cloud_name": "dxhqpbo96"
  });
  cl.pictureTag("samples/people/bicycle").toHtml()
```
The error it offers is that failed to map on undefined.

## Possible Reason
The possible reason is that pictureTag(publicId, options) function in cloudinary.js is invoking the PictureTag constructor without the 3rd parameter of sources as seen in the PictureTag constructor. In the overridden method of content, we are trying to map over an element which would be undefined if called from the pictureTag() helper function. The test case for picture tag does not use this helper function, rather constructs a picture tag from constructor itself.

##Update
Adding en error snapshot
![image](https://user-images.githubusercontent.com/959476/64912129-7e69f080-d748-11e9-98f1-d525450bfc67.png)

**Comment by const-cloudinary** [comment]
Hi @love2dishtech ,

Thank you for reaching out! 

We checked the code, it is a bug in this helper function. We opened an internal ticket for fixing it. Meanwhile you can use PictureTag constructor and pass relevant config (cloud_name) in the second parameter.

**Comment by patrick-tolosa** [comment]
Hey @love2dishtech 

We're replanning the picture tag solution in the next generation 
SDKs https://github.com/cloudinary/frontend-frameworks

But, we're rethinking the entire solution around picture tag and we may implement a different solution at the end.
Please watch the new repo for more updates.

Closing, as this will not be resolved in this project at this point.
