### ISSUE TITLE
Property 'new' is a static member of type 'Cloudinary'

### ISSUE THREAD

**Issue by davidhan527** [cloudinary/cloudinary_js#192]
Sorry if this is a basic question but I'm very new to typescript and I'm having trouble with getting Cloudinary to work with typescript.

Here are the relevant parts of the file.

```
import "cloudinary-video-player/dist/cld-video-player.min.css";
import cloudinary from "cloudinary-core";
import "cloudinary-video-player/dist/cld-video-player.min.js";

const VideoPlayer = props => {
  const cld = cloudinary.Cloudinary.new({ cloud_name: "dombgxi4e" });
}
```

and I get this error
```
TS2576: Property 'new' is a static member of type 'Cloudinary'
Failed to compile.
```

Any ideas how to fix this error?

**Comment by michalkcloudinay** [comment]
Hi @davidhan527,  Currently we don’t support typescript with our video player. You can embed the video player in a javascript project.

**Comment by PaulPCIO** [comment]
@michalkcloudinay this seems to be a problem with the typing of `import cloudinary from "cloudinary-core"` and nothing with the video player, I do not understand why this issue has been closed?

**Comment by maoznir** [comment]
Hi @PaulPCIO does this solve it for you?
```
import {Cloudinary} from 'cloudinary-core';
const cld = new Cloudinary({cloud_name: "demo"});
```

**Comment by PaulPCIO** [comment]
Yea that solved it! thanks
