### ISSUE TITLE
Auto-Generate Video Previews does not work

### ISSUE THREAD

**Issue by michalpalenkar** [cloudinary/cloudinary_js#210]
## Issue and Reproduction steps
Apply effect transformation according to this cloudinary feature [Generate an AI-based video preview](https://cloudinary.com/documentation/video_manipulation_and_delivery#generate_an_ai_based_video_preview)

Example:
`cl.video_url(publicId, { effect: "preview:duration_12"})
`

It returns invalid url, where this effect is serialized wrong as "**e_preview:du_8**", which results in response 400

`https://res.cloudinary.com/{cloudName}/video/upload/e_preview:du_8/{publicId}`

**Comment by aditimadan-Cloudinary** [comment]
Can you please share the account's cloud name and public_id of the resource and I will be able to pull up the logs and check further. You can always share the details by opening a support ticket here: https://support.cloudinary.com/hc/en-us/requests/new

**Comment by michalpalenkar** [comment]
Submitted #111311

**Comment by maoznir** [comment]
Closing this as it was fixed in Version 2.9.0
