### ISSUE TITLE
Bug: cname is overridden by secure

### ISSUE THREAD

**Issue by jamesarosen** [cloudinary/cloudinary_js#213]
This will use `res.cloudinary.com`
```js
new cloudinary.Cloudinary({
  cname: 'media.example.com',
  cloud_name: 'example',
  secure: true,
})
```
but this will use `media.example.com`:
```js
new cloudinary.Cloudinary({
  cname: 'media.example.com',
  cloud_name: 'example',
})
```
That's because of the `if/else` logic [here](https://github.com/cloudinary/cloudinary_js/blob/42f9795a6f3a624ba0d3565eb8cecd30f4a55e19/src/url.js#L105-L120).

Either (a) `secure` should only control the scheme or (b) the conflict should be documented.

**Comment by aleksandar-cloudinary** [comment]
Hi @jamesarosen. When using 'secure' you also need to provide the 'secure_distribution' parameter. That's the same as the 'cname' but is used when building secure URLs. Please include that in your code and the URLs will use that domain and not the shared res.cloudinary.com. You can refer to the documentation regarding SDK parameters here -
https://cloudinary.com/documentation/cloudinary_sdks?#configuration_parameters
Please let me know how it goes.

**Comment by jamesarosen** [comment]
That works 👍

**Comment by jamesarosen** [comment]
I was mistaken.
```js
```

**Comment by jamesarosen** [comment]
I was mistaken
```js
new cloudinary.Cloudinary({
  cloud_name: 'everlane',
  secure: true,
  secure_distribution: 'media.everlane.com',
})
```
results in URLs like
```
https://media.example.com/example/image/upload/w_auto/v1/my-image.jpg
```
But that URL doesn't resolve in Cloudinary's network. It needs to be

```
https://media.example.com/image/upload/w_auto/v1/my-image.jpg
```
(without the `/example` in the path)

**Comment by aleksandar-cloudinary** [comment]
You'll need to include 'private_cdn' parameter in addition so that the cloud_name is not included in the path.

**Comment by jamesarosen** [comment]
`private_cdn: true` works.

Since `private_cdn: false, secure_distribution: 'anything'` can't work, it would be nice if it at least warned me rather than emitting an invalid URL.

**Comment by aleksandar-cloudinary** [comment]
One reason we don't warn in such cases is that for basic setups 1 x CNAME => 1 cloud you won't need the cloud name in the path. However, we also support so that a single CNAME can be used for multiple clouds and in those cases the cloud_name needs to be part of the path hence private_cdn would need to remain false.
