### ISSUE TITLE
Package cloudinary-core -  Web bundle size - Can be smaller?

### ISSUE THREAD

**Issue by yoadsn** [cloudinary/cloudinary_js#238]
## Describe the bug in a sentence or two.

Using the latest version - bundle size kept growing over the past couple of versions.
https://bundlephobia.com/result?p=cloudinary-core@2.9.0
It is now at 82KB minified.

All I need this package is to generate the image URLs using a predefined set of transformations. Still, I have to pull in such a huge package that cannot be tree shaken using webpack.
(explicitly, I only call `config()` and `url()`)

Do I have another option to just generate the image URLs in a safe and compatible way or this is the smallest offer you have on the SDK side?
There is [this](https://github.com/esbenp/cloudinary-url-resolver) 3rd party lib for example but it does not seem well maintained and most likely could suffer from feature incompatibility.

Ideally, there would be an sdk which is event smaller than core only used for "display" purposes without the entire upload features. Even better, this packages could be tree shaken from all the code which is not required. (need to use sideEffects modifier for webpack to eliminate unused code)

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[X] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behavior
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files

## Versions and Libraries (fill in the version numbers)
Cloudinary-Core SDK version - 2.9.0

## Config Files (Please paste the following files if possible)
Probably not relevant

**Comment by maoznir** [comment]
Hi @yoadsn,
Unfortunately there is no smaller offering right now, but we are hard at work on a total rewrite of our javascript sdks. Bundle size and letting users import only what they need are among our top concerns.

I'll share your request with everyone who's involved, and update here when I can.
Meanwhile if you'd like, you can read more about our plans for the Javascript SDKs here: https://cloudinary.com/blog/get_ready_for_cloudinary_s_next_generation_javascript_sdks

**Comment by yoadsn** [comment]
@maoznir After reading the aforementioned docs - Can't wait for the new SDK :)
Thanks!
