### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ollym** [cloudinary/cloudinary_js#261]
Please make a new release with this:
https://github.com/cloudinary/cloudinary_js/commit/cce85547ae264becc93b858c44f26b63dc9e855f

As currently cloudinary_gem is broken because fetch_assets task only downloads named releases, which those changes are not included in any named release yet.

**Comment by maoznir** [comment]
Hi @ollym thanks for letting us know, the Cloudinary Ruby SDK has been updated to version 1.18.1 which includes the fix.
Please let us know if this solves the issue for you.

**Comment by ollym** [comment]
Thanks, works good now.
