### ISSUE TITLE
cloudinary-core@2.11.3" has unmet peer dependency "lodash@>=4.0".

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary_js#262]
## Feature request for Cloudinary JS SDK
Start using lodash-es

## Explain your use case
Smaller bundle sizes

**Comment by strausr** [comment]
@bjornharvold Thank you for your feedback.
Please note that we are indeed planning on removing lodash dependability in the future. However, when we tested lodash-es with cloudinary-core we found an overall increase in bundle size.

Lodash-es indeed has a smaller bundle size but there is a smaller bundle size for individual lodash utility packages when compared to lodash-es. We start to see a difference in bundle size when the number of individual lodash utility packages rises, then, the bundle size when lodash-es is used is smaller.

**Comment by maoznir** [comment]
Hi @bjornharvold, In addition to @strausr's comment, 
I'd like to add that we are hard at work on a total rewrite of our javascript sdks. Bundle size and letting users import only what they need are among our top concerns.

If you'd like, you can read more about our plans for the Javascript SDKs here: https://cloudinary.com/blog/get_ready_for_cloudinary_s_next_generation_javascript_sdks

**Comment by bjornharvold** [comment]
Thank you for feedback @strausr and @maoznir. You guys are doing great work!!
