### ISSUE TITLE
Overflow issues when opening the Upload widget.

### ISSUE THREAD

**Issue by nerdophile** [cloudinary/cloudinary_js#273]
Hi guys, I have been working on upload widget on my admin panel, so my panel has his viewport height fixed as 100vh and width as 100vw and  I have set the overflow to hidden at the body. Problem is when I open the widget the screen automatically overflows and my layout is broken. Refreshing the browser doesn't change anything and I have to navigate to different to page to fix it. 

## Issue Type (Can be multiple)
UI Issue

## Steps to reproduce
Can be reproduce my setting Viewport height and width to 100vh and 100vw respectively and setting overflow to hidden in the body and having a div inside of the body with overflow-y as auto and height: 100%. This Div should contain Upload widget.

## Error screenshots 
Before opening the widget
![image](https://user-images.githubusercontent.com/35519213/133045958-92501839-c967-4a88-aac0-381abfdff6ac.png)

After opening the widget 
![image](https://user-images.githubusercontent.com/35519213/133046057-3acce611-8b24-4f5b-8024-502004de3e3f.png)

As you can see in the background, the layout disappears and I cant figure out why its happening 

## Browsers (if issue relates to UI, else ignore)
Can be reproduced in all the browsers 

## Versions and Libraries (fill in the version numbers)
Latest version of all.js which is included in the script.

**Comment by michalkcloudinay** [comment]
Hi @nerdophile, Can you please open a support ticket at: https://support.cloudinary.com/hc/en-us/requests/new, and include your code and a link to your webpage so we can further assist? As this issue is not related to the js SDK I will go ahead and close this thread. Thanks.
