### ISSUE TITLE
jQuery.isFunction is deprecated (not available in v4 of jQuery)

### ISSUE THREAD

**Issue by RWAP** [cloudinary/cloudinary_js#294]
## Bug report for Cloudinary Cloudinary-JS SDK
Using latest version

## Describe the bug in a sentence or two.
jQuery.cloudinary.js reports "Uncaught TypeError: jQuery.isFunction is not a function" in line 537 when attempting to initialise under jquery v4

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[x ] Other (Specify)

Error reported on initialisation

## Steps to reproduce
Try installing the jquery SDK with jQuery v4 (beta release)
https://releases.jquery.com/git/jquery-git.js

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[X ] All

## Versions and Libraries (fill in the version numbers)
Cloudinary-Core SDK version
Node - 0.0.0
NPM - 0.0.0

## Config Files (Please paste the following files if possible)
Package.json
Webpack.config
Babelrc

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by wissam-khalili** [comment]
Hi @RWAP ,

Thank you for your feedback.
We are looking over this issue internally and we will be sure to keep you posted.

Regards,
Wissam

**Comment by strausr** [comment]
Hello @RWAP, please see the latest [release](https://github.com/cloudinary/cloudinary_js/releases/tag/2.13.1)
