### ISSUE TITLE
cloudinary_fileupload() called upon script inclusion

### ISSUE THREAD

**Issue by fabriziomoscon** [cloudinary/cloudinary_js#30]
Please see this commit:
https://github.com/cloudinary/cloudinary_js/commit/05cd1ec379f69719e3a01404de813a32351fe8dd

In this way `cloudinary_fileupload()` is called as soon as `jquery.cloudinary.js` is loaded which is far too early for initializing blueimpFileupload (at least in case the you wish to customize the options passed like in my case). At this point I haven't initialized `api_key` and `cloud_name` or other binding callbacks.
I want to pass more `options` so I call later on:

```javascript
$(".cloudinary_fileupload").cloudinary_fileupload(myCustomOptions);
```

Could the maintainer explain what is the correct usage in case I want to pass my own options such as `maxFileSize`, `dataType`, `headers`?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
