### ISSUE TITLE
Use automatic dpr in background images

### ISSUE THREAD

**Issue by Linuus** [cloudinary/cloudinary_js#34]
Hi

I'm using automatic dpr for my regular image tags and that works great. However, in some places I have images set as backgrounds of a `div`.
Does the cloudinary library have support for this use case as well?

**Comment by joelcuevas** [comment]
Hi! Is there any update about this? Is still not supported?

**Comment by eyalktCloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com, or create a new ticket if you have any additional issues.
