### ISSUE TITLE
No default for crop option in $.cloudinary.url()

### ISSUE THREAD

**Issue by dunghopper** [cloudinary/cloudinary_js#37]
The transformation documentation indicates that 'scale' is the default crop mode. Crafting urls directly, this is shown to be accurate: using `w_500` yields an identical result to `w_500,c_scale`.

I expect the javascript library to work the same way: it seems to me the following calls should result in different urls, but identical images:

```
$.cloudinary.url( public_id, { width: 500 } )
// expected: http://res.cloudinary.com/demo/image/upload/w_500/public_id.jpg
// actual: http://res.cloudinary.com/demo/image/upload/public_id.jpg ! No transformation !

$.cloudinary.url( public_id, { width: 500, crop: 'scale' } )
// http://res.cloudinary.com/demo/image/upload/w_500,c_scale/public_id.jpg
```

This unexpected behavior is due to the following code in `process_html_dimensions(options)`

```
if (!crop && !has_layer) {
      delete options.width;
      delete options.height;
}
```

I don't see any reason for deleting the requested width and height transformations in the absence of an explicit crop option, nor any documentation for the resulting surprising behavior. Is there some edge case that would be damaged by removing this code?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
