### ISSUE TITLE
Plain cloudinary.js for API-level access without jQuery

### ISSUE THREAD

**Issue by blast-hardcheese** [cloudinary/cloudinary_js#38]
Is there any real demand for a jQuery-less Cloudinary API? I'd like to use Cloudinary, but my site doesn't use jQuery anywhere else; I'd rather not include it just for Cloudinary.

**Comment by twler** [comment]
+1

**Comment by dettier** [comment]
+1

**Comment by websirnik** [comment]
+1

**Comment by cedricmay** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by csaintc** [comment]
:+1:

**Comment by Ugoku** [comment]
@tocker any news on this? Issue #52 mentions Cloudinary is working on this, is there a preliminary version we can try out?
Is there anything we can do to help?

**Comment by saystone** [comment]
+1

**Comment by peterzen** [comment]
+1

**Comment by tocker** [comment]
Hi all,

You can review the new code in the [detach-jquery](https://github.com/cloudinary/cloudinary_js/tree/feat/detach-jquery) branch. Keep in mind this is not production ready!
This version not only detaches jQuery but introduces a new API (while fully supporting the old one). See Chaining tests for more.

Your input will be greatly appreciated!

**Comment by Ugoku** [comment]
Awesome, will test this asap!

**Comment by tocker** [comment]
@blast-hardcheese @twler @dettier @websirnik @cedricmay @Ugoku @saystone @peterzen @antonholmquist 

### :loudspeaker: A new jQuery independent library has been released!
Full documentation is coming, but in the meantime you can refer to the [README.md](https://github.com/cloudinary/cloudinary_js/blob/master/README.md) and [API Reference](http://cloudinary.github.io/pkg-cloudinary-core).

Install using:
```shell
bower install cloudinary-core
```
or,
```shell
npm install cloudinary-core
```

Or get the sources directly from [this repository](https://github.com/cloudinary/cloudinary_js/tree/master/src) if that's your style...

***Let us know your experience with the new code!***

**Comment by twler** [comment]
Great, thanks! Will check it out and will keep evangelizing cloudinary!

**Comment by blast-hardcheese** [comment]
Solid, looking forward to using it!

**Comment by Ugoku** [comment]
Okay, finally had some time to look at it, here are my first thoughts:
- The jQuery dependency is gone, but now there's a dependency on lodash. lodash is smaller than jQuery (19 vs 29 kB gzipped) but that's still 19 kB of code that is largely unused.
- The new core library does not support uploading, it seems we still need the jQuery plugin for that.

It seems to me that for uploading files to Cloudinary in the browser I'm better off building my own script, as the core library only appears to be helpful for **retrieving** images. Is this correct?

**Comment by twler** [comment]
100% echo what @Ugoku said.  This looks like it is just factoring out the parts of the existing codebase that currently don't use jQuery and offering them as a subset, which isn't really that useful.  I'm hoping this is a first step to rewriting the whole thing in dependency-free JS.

We use lodash on the backend but requiring it on the frontend in place of jQuery doesn't feel like much of an improvement.

**Comment by tocker** [comment]
We hear you!
We've created a shrinkwrapped version of the core library.
Rather than recode the functions, the library includes the relevant subset of lodash functions - so there is no need to include the entire lodash.js library. The zipped library size is 17KB. 
You can take it for a test drive from [cloudinary/pkg-cloudinary-core](https://github.com/cloudinary/pkg-cloudinary-core/tree/feature/shrinkwrap).

**Comment by okeydoke** [comment]
+100

I'm trying to decipher how to POST images via xhr (eg without jQuery) Lack of documentation for anything other than jQuery plugins is really frustrating and the core library doesn't have support for file uploads

**Comment by blast-hardcheese** [comment]
Jessie, it's not really a solution, but just a friendly reminder that Chrome's network debugger has a "Copy as cURL" contextual menu item that completely replicates whatever request was copied via curl, the swiss-army network tool. Might help in reversing the request itself instead of trying to piece things together from browsing the code

**Comment by tocker** [comment]
Hi @okeydoke,
We created the core JavaScript in part to allow you to utilize any upload library you choose, or implement your own. Using an upload library has many advantages, but if you wish to implement your own upload function, see the documentation [here](http://cloudinary.com/documentation/upload_images#uploading_with_a_direct_call_to_the_api).

Use an [unsigned upload preset](http://cloudinary.com/documentation/upload_images#upload_presets) (which can be set [here](https://cloudinary.com/console/settings/upload#upload_presets)) to allow uploads without having to expose your API secret. 

I've prepared a short [example in JSFiddle](https://jsfiddle.net/tocker/fpoca4c8/) to demonstrate uploading to Cloudinary using pure JavaScript.

**Comment by tocker** [comment]
The shrinkwrap file is now part of the main package (version 2.0.6). It includes only the subset of the lodash functions which are in use by cloudinary.
If you prefer an "independent" implementation of the util functions you can implement your own utility file under the `util` folder and build the library with it (and share it with a PR :smile: ). 

We'll post detailed build instructions as soon as we can.

I'm closing this issue. @okeydoke if you still have an issue with the upload please open a separate issue or contact our support.

**Comment by hidace** [comment]
@tocker Is it possible to make transformations when directly posting to this API?
