### ISSUE TITLE
Uploading on mobile device needs smaller cloudinary_js

### ISSUE THREAD

**Issue by huanglong-zz** [cloudinary/cloudinary_js#42]
Yeah, My website has used cloudinary for a long time on pc and we paid for better bandwidth.

But we are working on mobile web pages right now which requires image upload function too. And the cloudinary_js requires jquery image upload stuff which is really huge to load.

I am just wondering if you nice guys could supply a version of cloudnary_js supported by zepto.js?

**Comment by tocker** [comment]
Hi @huanglong, we are using Blueimp File Upload as a reference implementation.
If your mobile web page requires streamlined upload code, I suggest that you use our [jquery without upload](https://github.com/cloudinary/pkg-cloudinary-jquery) library and implement a bespoke upload function.

**Comment by maoznir** [comment]
Closing due to time passed

**Comment by eyalktCloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or contact our support at http://support.cloudinary.com
