### ISSUE TITLE
Ability to use progressive jpeg option

### ISSUE THREAD

**Issue by florent-blanvillain** [cloudinary/cloudinary_js#45]
It seems like there is no options in this api to get a progressive jpeg image, would it be possible to add it ?

**Comment by tocker** [comment]
Hi @florent-blanvillain,

You can get a progressive jpeg by using the `progressive` flag.
For example `http://res.cloudinary.com/demo/image/upload/fl_progressive/sample.jpg`
produces:
![progressive jpeg](http://res.cloudinary.com/demo/image/upload/fl_progressive/sample.jpg).

**Comment by tocker** [comment]
Hi @florent-blanvillain,

I hope my answer solved your issue. I'm closing this due to the elapsed time, but please feel free to reopen this issue or submit a new issue if you need to.

@tocker

**Comment by florent-blanvillain** [comment]
Thanks tocker, I did manage to tweak the url computed by cloudinary.js to add the option. It's not ideal, but ok.
