### ISSUE TITLE
Issue with stock Android 4.x browser

### ISSUE THREAD

**Issue by marvoh** [cloudinary/cloudinary_js#46]
This doesn't work with the stock android browser due to a jquery bug.

**Comment by taragano** [comment]
This seems to be a Phonegap issue.
The following SO answer suggests that it works in an iFrame:
http://stackoverflow.com/questions/23739254/how-to-enable-file-upload-in-phonegap-inappbrowser

**Comment by marvoh** [comment]
I already overcame this by using angularjs and no it's not a phonegapp issue

**Comment by taragano** [comment]
Thank you for the update, I'm glad you've found a solution to this.

Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
