### ISSUE TITLE
Unable to upload file using AngularJS

### ISSUE THREAD

**Issue by karry89** [cloudinary/cloudinary_js#49]
I tried to upload file using ngFileUpload module and POST it to cloudinary server (Direct upload from client Side). I enabled unsigned upload from the Cloudinary console and used the upload_preset in the code. I can see the event happening but POST throws and error, "Upload preset must be specified when using unsigned upload". 400 (Bad Request)

        $scope.upload_cloudinary = function(files){
            //console.log($scope.$watch);
            console.log("Cloud Name: "+$.cloudinary.config().cloud_name+"Upload Preset: "+$.cloudinary.config().upload_preset);
            console.log();
            if(files && files.length){
                for(var i =0; i<files.length; i++){
                    var file = files[i];
                    Upload.upload({
                        url: "https://api.cloudinary.com/v1_1/" + $.cloudinary.config().cloud_name + "/upload",
                        data: {upload_preset: $.cloudinary.config().upload_preset, tags: 'UserProfilePics', context:'ProfilePics=' + $scope.title},
                        file:file
                    }).progress(function(e){
                        //console.log(evt);
                        file.progress = Math.round((e.loaded * 100.0) / e.total);
                        console.log("Uploading... " + file.progress + "%");
                    }).success(function(data, status, headers, config){
                        console.log(data, status, headers, config);
                    });
                }
            }
            else{
                $bootbox.alert("No Image selected! You shall be grounded! >(");
            }
        };

**Comment by taragano** [comment]
I'm very sorry for the response delay.
In case you still experience this issue, please share a URL to a live webpage where this issue is demonstrated and we'll be happy to take a deeper look.

Thanks

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
