### ISSUE TITLE
width and height options are not included in src

### ISSUE THREAD

**Issue by mollerhoj** [cloudinary/cloudinary_js#54]
```
    $.cloudinary.url(image_id, {width: 10, height: 10})
```
yields
```
http://res.cloudinary.com/cloud_name/image/upload/image_id.png
```
The same is true for `$.cloudinary.image`. The `src` does not include the width and height properties.

**Comment by tocker** [comment]
Hi @mollerhoj,

You need to add a crop mode for the transformation to be applied. For example:

    $.cloudinary.url(image_id, {width: 10, height: 10, crop: "fill"})

See more information [here](http://cloudinary.com/documentation/image_transformations#crop_modes).

**Comment by tocker** [comment]
I hope that worked for you!
Closing due to elapsed time. Feel free to reopen or create a new issue.
