### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by csaintc** [cloudinary/cloudinary_js#55]
I'm currently using npm to manage my project's dependencies.

All of this projects dependencies have an NPM repo, why doesn't this project have an npm repo?

**Comment by creatorrr** [comment]
Any update on this? Why was this issue closed, @csaintc?

**Comment by tocker** [comment]
@csaintc and @creatorrr - We just released a major version. The full library (equivalent to `jquery.cloudinary.js`) is [cloudinary-jquery-file-upload](https://github.com/cloudinary/cloudinary-jquery-file-upload). A jQuery-independent version is also available. Refer to the [README](https://github.com/cloudinary/cloudinary_js/blob/master/README.md) file for more details

You can install it with npm:
```shell
npm install cloudinary-jquery-file-upload
```

@creatorrr - issue was closed by @csaintc.

**Comment by creatorrr** [comment]
Hey @tocker, thanks for the reply. It seems that, as of posting this comment, the github repo you linked to and the npm package still have to be uploaded. Awaiting in earnest. 

Meanwhile, I've made a temporary npm package for the repo: [jquery.cloudinary](https://www.npmjs.com/package/jquery.cloudinary). Happy to give over the npm access to cloudinary if necessary.

**Comment by tocker** [comment]
@creatorrr - libraries are on npm now.
Thanks for creating the npm package and again for offering to hand over the access!
It may be best to [deprecate](https://docs.npmjs.com/cli/deprecate) the package with a message redirecting to the new package so that developers will not get confused.

If you still wish to hand over the access, our NPM user is `cloudinary` (obviously).

**Comment by creatorrr** [comment]
@tocker It seems that transferring a package is [non-trivial](https://github.com/npm/npm/issues/7515) so I have deprecated the previous package. Let me know if you want me to unpublish it as well. Thanks for the great work!
