### ISSUE TITLE
problem with cloudinary_cors.html in IE8 - windows 7

### ISSUE THREAD

**Issue by RShergold** [cloudinary/cloudinary_js#56]
When uploading an image in Internet Explorer 8 i get an error on [this line](https://github.com/cloudinary/cloudinary_js/blob/master/html/cloudinary_cors.html#L39) of the cloudinary_cors.html file.

It seems that document.body doesn't have method hasOwnProperty in IE8. It's strange because the comment above this line seems to be saying that this is an explicit check to see if we are running on less than IE9. I removed the if statement and set it to always run 

    document.body.innerText = parse(window.location.search.slice(1));

and now it seems to run fine.

The commit that made this change stated it was to [protect against a XSS vulnerability](https://github.com/cloudinary/cloudinary_js/commit/dffe2a4f35c382e0f017b791ac02f059c0120d02)

Is it safe for me to make this change or is there another cause to my problem you can think of?

**Comment by tocker** [comment]
@RShergold Thanks for letting us know!
We are issuing a fix for this issue.
