### ISSUE TITLE
$.cloudinary.image with width="auto" does not set the data-src attribute

### ISSUE THREAD

**Issue by bartocc** [cloudinary/cloudinary_js#58]
I read [on this cloudinary's blog article](http://cloudinary.com/blog/how_to_automatically_create_images_for_responsive_design#api_example_1) that the SDKs would handle the width="auto" param and return an image with a blank `src` attribute and the `data-src` attribute set to the url to be used when calling $.cloudinary.responsive() but the img tag I get does not contain the `data-src` attribute.

Instead, the image function sets data("src-cache") (as of cloudinary_js 1.0.25)

```js
    image: function(public_id, options) {
      options = $.extend({}, options);
      var url = prepare_html_url(public_id, options);
      var img = $('<img/>').data('src-cache', url).attr(options).cloudinary_update(options);
      return img;
    },
```

This prevents $.cloudinary.responsive() to work.

Am I doing something wrong or is this a bug ?

Thanks.

**Comment by TalLevAmi** [comment]
As you can see [here] (https://github.com/cloudinary/cloudinary_js/blob/master/js/jquery.cloudinary.js#L790) the responsive code considers the data-src-cache attribute as well. Is something not working for you?

**Comment by bartocc** [comment]
Thank for pointing the cloudinary_update function @TalLevAmi 

I am now calling this explicitly on images with the "cld-responsive" class instead of using $.cloudinary.responsive()

I believe my issue was due to the use of cloudinary_js in an emberjs app. The img tag had not been inserted in the DOM at the time cloudinary_update was called.

BTW, are there any plans on converting and releasing cloudinary_js equivalents for SPA frameworks like ember or angular ?

**Comment by TalLevAmi** [comment]
We are working on a jQuery free version of the cloudinary_js library that's more lightweight. You can take a look at the progress here - https://github.com/cloudinary/cloudinary_js/tree/feat/detach-jquery
