### ISSUE TITLE
Add to CDN for easy deployment on production environments

### ISSUE THREAD

**Issue by holtkamp** [cloudinary/cloudinary_js#59]
To use the JavaScript functionality (compliments by the way ;)) on a production environment, hosting on a CDN (with focus on JavaScript packages) would be nice instead of hosting it ourselves. 

For the time being, RawGit suits fine, this converts a GitHub URL to a CDN like approach:
https://cdn.rawgit.com/cloudinary/cloudinary_js/master/js/jquery.cloudinary.js

But maybe you can consider registering it at something like www.cdnjs.com?

**Comment by taragano** [comment]
Thank you for your suggestion.

Please note that while our JS lib isn't currently present on cdnjs.com, you can upload the JS files to your own Cloudinary account and the image will be also delivered via Akamai's worldwide fast CDN.
For more information:
http://cloudinary.com/blog/using_cloudinary_to_manage_all_your_website_s_assets_in_the_cloud

**Comment by holtkamp** [comment]
@taragano, ok, also thanks for your suggestion ;). The reason why I prefer something like CDNJS is because we install assets like the Cloudinary plugin using Bower, which using semantic versioning. Uploading these files manually to a CDN isn't really 2015, CDNJS fetches them automatically as soon as a new version is tagged, additionally using a commonly used CDN increases the chance that a user already has the file in their browser cache.

**Comment by dohomi** [comment]
+1

**Comment by holtkamp** [comment]
Any new developments on this? Encountered the situation again were we are 'forced' to use RawGit, which is not really advised in production environments...

**Comment by holtkamp** [comment]
This issue is marked as being a question, I would say its an enhancement... Encountered it again.

**Comment by tocker** [comment]
Hi @holt Kamp, 

The Cloudinary JavaScript are now hosted on cdnjs. 

See https://cdnjs.com/#q=cloudinary

**Comment by holtkamp** [comment]
Nice @tocker ! Just a doubt, is the [jQuery package](https://github.com/cloudinary/pkg-cloudinary-jquery) also hosted there?

Looking at https://github.com/cloudinary/cloudinary_js#new-api, I can only find the following ones at the CDN:

- core
- jquery-file-upload

**Comment by holtkamp** [comment]
Bump on this? 

It also seems that no autoupdate mechanism is used since ```2.0.8``` is the last version on CDNJS

<img width="707" alt="screen shot 2016-06-30 at 16 12 11" src="https://cloud.githubusercontent.com/assets/776405/16491298/aeba0fce-3edd-11e6-8080-7b0eec3383c3.png">

Also see https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

Is there any way the community can help?

**Comment by tocker** [comment]
autoupdate *is* setup for the libraries. I'll check why they were not updated.

**Comment by holtkamp** [comment]
@tocker, running into this again. Auto update up untill ```2.1.2``` worked well, only it seems the NPM packages are not updated properly (anymore?)...

Also reported this at CDNJS: https://github.com/cdnjs/cdnjs/issues/8512#issuecomment-254157715

**Comment by holtkamp** [comment]
@tocker also see https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package on how to push an update to the NPM repo...

**Comment by tocker** [comment]
Released 2.1.5. cdnjs should pick it up in the next cycle.

**Comment by holtkamp** [comment]
@tocker do you mean you also **published** ```2.1.5``` to npm as mentioned in the provided link? ```2.1.5``` has been released for 2 weeks now and are still at ```2.1.2```, don't think this happens automatically...

https://www.npmjs.com/package/cloudinary-core
https://www.npmjs.com/package/cloudinary-jquery-file-upload

**Comment by tocker** [comment]
npm is up to date now.

**Comment by holtkamp** [comment]
@tocker great! CDNJS already picked it up 😄 

https://cdnjs.com/libraries/cloudinary-core
https://cdnjs.com/libraries/cloudinary-jquery-file-upload

Closing issue

**Comment by holtkamp** [comment]
Last remark on this, also see https://github.com/cloudinary/cloudinary_js/issues/59#issuecomment-223562508

**Working**
https://cdnjs.com/libraries/cloudinary-core
https://cdnjs.com/libraries/cloudinary-jquery-file-upload

**Missing**
https://cdnjs.com/libraries/cloudinary-jquery

Is this on purpose?

**Comment by tocker** [comment]
> Is this on purpose?

Simply a matter of priorities. We'll publish cloudinary-jquery to cdnjs very soon.
