### ISSUE TITLE
Incorrect width used when images marked as cld-responsive are part of inactive Bootstrap TabPanes

### ISSUE THREAD

**Issue by holtkamp** [cloudinary/cloudinary_js#60]
Based on [this nice article](http://cloudinary.com/blog/how_to_automatically_create_images_for_responsive_design), we tried to use the described responsive behaviour of images served by Cloudinary in a page that uses [Bootstrap TabPanels](http://getbootstrap.com/javascript/#tabs). This resulted in the following behaviour:

- the generated URLs for the images that are part of the initially active TabPane have proper widths: around 150 pixels for thumbnails.
- the generated URLs for the images that are part of the inactive TabPanes, the width of the TabPane (or the element containing the TabPane) is used: around 680 pixels in our design. 

The resulting images are displayed properly when a TabPane is activated. However, when being loaded an image with a bigger width than required is loaded. This kind of make using this feature useless, since we use TabPanels a lot.

Using the incorrect width is possibly caused by [this snippet of code](https://github.com/cloudinary/cloudinary_js/blob/f2e053c84bcb5664fec6099727df14a53fe93117/src/cloudinaryjquery.coffee#L121-L129) which traverses up to the DOM untill a proper width is found. As soon as the element is found that contains all the TabPanes, THAT width is used since that element is the first one visible... Maybe this approach is a bit 'naive'? Maybe the 'loading' process should only start when the element itself, or direct parent has a width, or make the amount of considered upper elements configurable? Then we could fire a ```window resize event``` as soon as a Tab is clicked...

Update, I [tested the last suggestion](https://github.com/holtkamp/cloudinary_js/commit/e002cb0cb00ae6dc4459655723b58c2581c9920f), this works properly. We take the size of the parentNode and fire a window.resize event as soon as a Tab is activated. In what scenario's would you want to traverse further 'up' the hierarchy than just the parent node of the image?

**Comment by tocker** [comment]
Confirmed.
Thanks for the detailed report!

**Comment by tocker** [comment]
Fixed in version 2.0.1

**Comment by holtkamp** [comment]
Thanks for the fix, just updated to ```2.0.1```. With this version it seems that images that are in an inactive TabPanel get assigned an unrounded width of ```w_16.6667``` in the URL used to request the image, which is marked as a ```HTTP 400 BadRequest```.

This occurs when the container of an responsive image element has a unrounded width, I am not sure what place is best to apply rounding, [maybe here](https://github.com/cloudinary/cloudinary_js/blob/0ecad1543c3447ac78a7fb5a129c7d58a9733c55/src/cloudinary.coffee#L553):

```javascript
containerWidth = Math.round(Util.width(element));
```

**Comment by holtkamp** [comment]
ping @tocker, we are currently in the acceptance-stage of a responsive design. This issue currently blocks production. Can you confirm this is on your / Cloudinary's radar?

**Comment by tocker** [comment]
Hi @holtkamp. We will issue a fix soon.

**Comment by holtkamp** [comment]
ok @tocker, thanks for the swift response!

**Comment by holtkamp** [comment]
@tocker , any update on this? We are now working on a [TypeAhead](https://twitter.github.io/typeahead.js/) based search mechanism. When a search term does not match a product, we display it and hide the others.

The continuous hiding / displaying of hundreds of products spread over various TabPanels causes a lot of clicks to be simulated on the Tabs. Each time this happens, the dimensions for the responsive images are recalculated and the images are fetched from Cloudinary, drastically decreasing performance. Hope this underlines the rationale a bit ;)

**Comment by holtkamp** [comment]
shameless ping for @tocker :smiley:

**Comment by tocker** [comment]
@holtkamp sorry for the delay.
I was not able to reproduce your issue. Even with md-col I'm getting a specific pixel width.

Can you please share the relevant code and configuration required to reproduce the problem?
(You can [open a ticket](http://support.cloudinary.com/hc/en-us/requests/new) and attach your files there if you don't wish to share them publically.)

**Comment by holtkamp** [comment]
@tocker, np. 

Just pushed an [example](https://github.com/holtkamp/cloudinary_js/blob/52721795c89267516ff4296ad700fe13a8de1682/html/bootstrap.grid.responsive.images.html) to my patch branch which has added rounding of the element's initial widths:
https://github.com/holtkamp/cloudinary_js/commit/75e409c97f96301098ed677181b874739c1761e5

If you *disable* that rounding, incorrect image URLs are generated as can be seen here:
![screen shot 2016-01-14 at 13 50 21](https://cloud.githubusercontent.com/assets/776405/12324918/977d7292-bac6-11e5-9c24-77cdbc596148.png)

It goes wrong with:
- 33.3333 col-md-4
- 16.6667 [col-md-2](https://github.com/twbs/bootstrap/blob/742d3ebcb5d68873ca16596a79879d55d9df1f21/dist/css/bootstrap.css#L1970-L1972)
- 8.33333 col-md-1


This example also depicts the 'problem' that we need to fire a resize event each time TabContent is activated by clicking a Tab. Would that be something that can be improved? Maybe with a Cloudinary <=> Bootstrap bridge plugin?

**Comment by tocker** [comment]
@holtkamp thanks! We'll test it. Which browser and what browser version are you testing with?

**Comment by holtkamp** [comment]
@tocker the following browsers on Mac OSX 10.11.2 issue a URL that result a HTTP 400 bad request

- Safari
- FireFox
- FireFox Developer Edition
- Chrome

**Comment by tocker** [comment]
Confirmed. Problem is reproducible with v1.0.25 as well.

**Comment by holtkamp** [comment]
Additionally, I noticed the following behaviour as a direct result of triggering the resize event after TabPane is displayed:
- the width of the images of the *active* TabPane will be determined, which is the purpose :smile: 
- the width of the images of the *inactive* TabPanes will also be re-determined. 
 - since the TabPane is hidden, these images will go back to the really small images. After they become active again, they will AGAIN be resized. 

So over all, this approach is not optimal. Particularly when a lot of images are involved in mainly hidden TabPanes (most heavy page has around 700 images, of which around 680 would be inactive at a time). 

Instead of triggering the resize event, it might be better to specifically update the relevant images:

```javascript
$("tab-pane.active img.cld-responsive").cloudinary_update();
```

And additionally, when switching a lot between tabs, it does not make sense to keep updating. I would only like to update those that actually NEED updating.

Extending the selector to only select those images that do not have a ```src``` attribute yet will not work, since they will all be assigned one when the page loads by ```cloudinary_update()``` (can't change this since other images that or not located in the TabPanes might also be responsive).

So lets keep track of it ourselves by setting a specific attribute, that will be removed when the window is resized:

```javascript
$.cloudinary.responsive();

$(document).on('shown.bs.tab', 'a[data-toggle="tab"]', function (event) {
    console.log("TabContent is displayed, make sure to update the images if they have not been updated yet", $(".tab-pane.active img.cld-responsive:not([data-cloudinary-responsive-url-updated])"));
    $(".tab-pane.active img.cld-responsive:not([data-cloudinary-responsive-url-updated])").cloudinary_update().each(function () {
        console.log("Image", $(this), "has attribute?", $(this).attr("data-cloudinary-responsive-url-updated") !== undefined);
        $(this).attr("data-cloudinary-responsive-url-updated", $.now()); //Assign a timestamp so changing TabPane will not trigger an update again
    });
});

$(window).resize(function () {
    console.log("Window resize detected, remove all flag attributes");
    $("img.cld-responsive[data-cloudinary-responsive-url-updated]").each(function () {
        console.log("Remove attributes acting as flag from", $(this));
        $(this).removeAttr("data-cloudinary-responsive-url-updated");
    });
});
	
```

Note that I use attributes and not HTML 5 data to set the flag so we can easily re-use them later in the JQuery selector.

**Comment by tocker** [comment]
Your **first issue** (percentage as width) is caused by the implementation of tab in Bootstrap. Specifically it uses `display: none` which prevents CSS from calculating the correct width.

You can solve this by adding the following CSS definition *after* loading the Bootstrap CSS:

```css
.tab-content > .tab-pane {
    display: block;
    visibility: hidden;
    position: fixed;
}
.tab-content > .active {
    display: block;
    visibility: visible;
}
```
:warning: `position:fixed` is required because all tabs are laid out. Test this solution to make sure it doesn't affect the overall page layout.

For example, you can put the above code in `responsive-tab.css`, and then edit your HTML as follows:

```html
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css">
<link rel="stylesheet" href="responsive-tab.css">
```

Your **second issue** occurs because you are triggering `resize` on tab change. There is no need to to that.

**Comment by tocker** [comment]
A "cleaner" solution: add the style before executing `cloudinary_update`, and remove it afterwards. This applies the aforementioned solution for the duration of the execution only.

Add the following code at the bottom of your HTML page:

```html
<script type="text/javascript">
    $(function(){
        // keep a reference to the original function
        var orig_update = $.fn.cloudinary_update;
        // wrap function call with the style fix
        $.fn.cloudinary_update = function(){
            var s = $('<style type="text/css">.tab-content > .tab-pane {display: block;visibility: hidden;position: fixed;}.tab-content > .active {display: block;visibility: visible;}</style>').appendTo('body');
            orig_update.apply(this, arguments);
            s.remove();
        };
        // now call responsive() as usual
        $.cloudinary.responsive();
    });
</script>
```

You can also place the code (from `//keep...` until `// now...`) in a separate JavaScript file and load it using a `<script>` tag *after* the cloudinary JS tag.

**Comment by holtkamp** [comment]
Ok thanks! Well I don't mind using the suggested style definitions after the Bootstrap style is loaded / blend it with Bootstrap while generating the CSS using LESS. But I am wondering 'why' the Bootstrap team would haven chosen the current ```display: none;``` approach. I think it has to do with:

- When simply adding the style to the example of my patch branch, it works.
- When applying it to our application which has a more complex structure with nested TabPanels, it messes up the style / layout and the functioning of nested TabPanels. 
- When temporarily applying the style when running the cloudinary_update() function, it seems to work as expected, all images are loaded properly, also the ones in hidden TabPanes. It does feel a bit like a hack though :grin: 

Will try to come up with an example that uses some nested TabPanels to illustrate this 'issue' this week.

**Comment by tocker** [comment]
According to the bootstrap site, nested tabs are not supported (see [here](http://getbootstrap.com/javascript/#tabs-examples)).

**Comment by holtkamp** [comment]
Well, we have been using them for quite some time, I think that part of the documentation indicates that a Tab within a Tab is not supported. But when Using "TabPanels", one typically got Tabs to activate one or more TabPanes. The content of a TabPane can contain new TabPanels AFAIK. [Just pushed an example from our designs which depicts our use case.](https://github.com/holtkamp/cloudinary_js/blob/patch-1/html/bootstrap.grid.responsive.images.TabPanels.html). It *is* quite big, but your suggestion to temporarily add some CSS works...

**Comment by holtkamp** [comment]
@tocker, I searched a bit on the CSS part and found [this post](http://stackoverflow.com/a/23267110/187659). The CSS suggested in that post slightly differs from your CSS but does not mangle the layout of pages that contains multiple TabPanels. Concluding, this seems to work and does not require overriding the ```cloudinary_update()``` function:

```css
        .tab-content > .tab-pane {
            display: block;     /* undo display:none          */
            height: 0;          /* height:0 is also invisible */
            overflow-y: hidden; /* no-overflow                */
        }
        .tab-content > .active {
             height: auto;       /* let the content decide it  */
        }
```

I think this issue can be closed, agree? Thanks for the in-depth support, seems rare among commercial companies nowadays ;).

**Comment by tocker** [comment]
No problem!
Thanks for the link to the stackoverflow answer.

**Comment by holtkamp** [comment]
Final word of caution for others reaching this issue. When using the suggested CSS to apply *permanently*. This changes the way the TabPanels are rendered on the page, they are placed 'after' each other / stacked. This might lead to confusing results when trying to use the Bootstrap Affix plugin on other TabPanes than the first one since the element offsets are absolute. Using  the 'change the CSS while updating the images' approach does not have this downside.
