### ISSUE TITLE
Make classname to activate 'responsive images' configurable

### ISSUE THREAD

**Issue by holtkamp** [cloudinary/cloudinary_js#62]
Currently the classname to apply the 'responsive' functionality is [hard-coded](https://github.com/cloudinary/cloudinary_js/blob/0ecad1543c3447ac78a7fb5a129c7d58a9733c55/src/cloudinaryjquery.coffee#L37) to ```cld-responsive```. "Why?" was the first thing that popped in to mind. Why not make it configurable while having a default value of ```cld-responsive```? 

This makes the Cloudinary library less obtrusive and therefore better adoptable. For examples, all our responsive images already have assigned a classname ```responsive``` which can then be 'reused'.

**Comment by holtkamp** [comment]
I appears this is made configurable by now?

https://github.com/cloudinary/cloudinary_js/blob/3e716e586e6a8b300279225890921448b807e75c/js/jquery.cloudinary.js#L1864

**Comment by tocker** [comment]
Correct. This was implemented in [version 2.0.7](https://github.com/cloudinary/cloudinary_js/releases/tag/2.0.7)
