### ISSUE TITLE
cloudinary-jquery doesn't work with the upload widget

### ISSUE THREAD

**Issue by charlierudolph** [cloudinary/cloudinary_js#63]
http://cloudinary.com/documentation/upload_widget

I had used both together with 1.0.25, but as of 2.0.0, the fact that they both set the window.cloudinary causes issues.

**Comment by tocker** [comment]
Hi @charlierudolph,
This has been fixed.
Can you please retest on your side?

**Comment by tocker** [comment]
@charlierudolph closing this issue. 
Please open a new issue if you still have problems with the widget!
