### ISSUE TITLE
this.fileupload is not a function

### ISSUE THREAD

**Issue by danconnell** [cloudinary/cloudinary_js#64]
2.0.1 works for me, but on 2.0.3 I get a runtime error of `Uncaught TypeError: this.fileupload is not a function`.

Error occurs at line 3307 of cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js.
![screenshot 2015-11-30 03 31 09](https://cloud.githubusercontent.com/assets/2864564/11483655/929d84be-9777-11e5-9057-d98a95688390.png)

**Comment by tocker** [comment]
Hi @danconnell, 

The major change between 2.0.1 and 2.0.3 was bootstrapping the upload code (see [code](https://github.com/cloudinary/cloudinary_js/blob/master/src/jquery-file-upload.coffee#L11-L13)). This behaviour, from version 1.x, was left out from 2.0.0 but brought back to keep the code backward compatible.

Please make sure that you are loading the Cloudinary JavaScript file *after* loading the Blueimp files, specifically `jquery.fileupload.js`.

**Comment by danconnell** [comment]
Alright. Thanks, @tocker.
