### ISSUE TITLE
Cloudinary Upload Widget messing up button's text when using custom stylesheet

### ISSUE THREAD

**Issue by deenison** [cloudinary/cloudinary_js#66]
Here is an example scenario:
Let's say we have a button. Once this button is clicked, the widget is open.
```javascript
$('#btn-upload-sample').on('click', function() {
    ...
    cloudinary.openUploadWidget(options, function(error, result) {...}
}
```
Let's say we've configured the widget with the following settings:
```javascript
var options = {
    cloud_name: "foo",
    upload_preset: "whatever",
    multiple: false,
    text: {
        'sources.local.select_file' : "Choose a file..."
    }
};
```
Since we defined `multiple: false`, inside the widget's modal, the "Select File" button's text should reflect the parameter `sources.local.select_file` that we've set. When the widget is opened, the button displays "Choose a file..." as it should. Everything is ok so far.

But if we add any custom stylesheet to our widget (let's say it can be found at   `//yourdomain.com/assets/css/cloudinary-widget.min.css`)
```javascript
var options = {
    cloud_name: "foo",
    upload_preset: "whatever",
    multiple: false,
    text: {
        'sources.local.select_file' : "Choose a file..."
    },
    stylesheet: "//yourdomain.com/assets/css/cloudinary-widget.min.css"
};
```
and then refresh the page and open the widget again, the same button displays "Select files" (or whatever we put on `sources.local.select_files` in `text` parameter). 

It seems that when we have a custom stylesheet, the widget ignores the `multiple` parameter when it's deciding which text should be inside the button, the "single" or "multiple" one. The upload itself is not affected btw, only the text.

Best regards.

**Comment by tocker** [comment]
Hi @deenison, the widget is not part of this repository. Can you please open a request at http://support.cloudinary.com/hc/en-us/requests/new instead and close this issue?

**Comment by deenison** [comment]
Sure @tocker, my bad, just sent them the issue.
Thanks.
