### ISSUE TITLE
hard fileupload dependency introduced in 2.0.2

### ISSUE THREAD

**Issue by romanbsd** [cloudinary/cloudinary_js#67]
This commit 7b9ee40724053abe63c7de90d6746bac89766cb8 introduces a hard dependency on the fileupload plugin. When it's not included, it crashes.
For the user app we are using cloudinary only for displaying of images, so we don't need the fileupload.
As a bonus it would be nice if there was a smaller build which doesn't include the uploading capabilities at all.

**Comment by tocker** [comment]
Hi @romanbsd,

Sorry for the delay. If you are not using the upload capabilities, you should use [cloudinary-core](https://github.com/cloudinary/pkg-cloudinary-core) or [cloudinary-jquery](https://github.com/cloudinary/pkg-cloudinary-jquery) (which includes the jQuery plugin but not the fileupload functionality). This was the major reason for version 2.

If you are using bower you can get them using `bower install cloudinary-core` etc.
