### ISSUE TITLE
Lodash is now a dependency too?

### ISSUE THREAD

**Issue by twler** [cloudinary/cloudinary_js#68]
I'm doing file uploads from the client.  I have to include jQuery as a dependency, which I understand is being removed eventually.

In the meantime I'm maintaining my app and updating bower, and including the libraries as suggested:

      './src/bower_components/cloudinary-core/cloudinary-core.js'
      './src/bower_components/cloudinary-jquery/cloudinary-jquery.js'
      './src/bower_components/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js'

I get `Uncaught ReferenceError: _ is not defined`

Adding lodash in front of them solves this.

**Does this mean that the file upload is now dependent on lodash and jQuery both?  Or am I missing something and there is a way around this?**

Also as feedback, our team would strongly prefer that the cloudinary libraries be fully independent of external libraries.

**Comment by tocker** [comment]
Hi @twler,

You only need to include one of the lines above. If you are using the jQuery File upload, just include the last one: 

```
 './src/bower_components/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js'
```

**Comment by twler** [comment]
Thanks @tocker 
Dependencies aren't very clear in the docs; see https://github.com/cloudinary/cloudinary_js/issues/69 for what I ended up needing in this case.
