### ISSUE TITLE
Trouble uploading unsigned via new jquery-file-upload

### ISSUE THREAD

**Issue by twler** [cloudinary/cloudinary_js#69]
I'm trying to do an unsigned upload that was working fine with the previous version of file upload, but now I can't seem to get it configured.  Trying to cobble together from the docs here http://cloudinary.com/documentation/jquery_image_upload

HTML

    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js"></script>
    ...
    <input type="file" name="file" class="cloudinary-fileupload" 
      data-form-data="%7B%22upload_preset%22:%22logo_260x60%22,%22cloud_name%22:%22mysite%22,%22tags%22:%22browser_uploads%22%7D"/>

JS

    $.cloudinary.config({ cloud_name: 'mysite' })

The input shows up and lets me select a file, but never initiates an upload.  No errors, no message in the console, nothing.

What more is needed?

**Comment by nadavofi** [comment]
Try including the following .js files (in that precise order):
* jquery.min.js
* jquery-ui.min.js
* jquery.fileupload.js
* jquery.iframe-transport.js
* cloudinary-jquery-file-upload.js

This should do the trick.

**Comment by twler** [comment]
Thanks -- this works, though with:

    bower_components/jquery/dist/jquery.js
    bower_components/jquery.ui/ui/widget.js
    bower_components/blueimp-file-upload/js/jquery.fileupload.js
    bower_components/blueimp-file-upload/js/jquery.iframe-transport.js
    bower_components/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js

My only remaining suggestion would be to document the dependencies better, since it isn't clear now.
