### ISSUE TITLE
Always receive invalid signature response when adding any params besides api_key, timestamp, signature, or resource_type

### ISSUE THREAD

**Issue by mitchellporter** [cloudinary/cloudinary_js#72]
This issue has been driving me nuts for the past 2 days. I can successfully generate a signature and upload a video file using the following code:

``` Javascript
var parametersString = 'timestamp=' + timestamp + cloudinaryAPISecret
shasum.update(parametersString);

var signature = shasum.digest('hex');

var dict = {};
dict['api_key'] = cloudinaryAPIKey;
dict['timestamp'] = timestamp;
dict['signature'] = signature;
dict['resource_type'] = 'video';
```

I return the dictionary to my iOS app and pass it as the `options` parameter to the cloudinary SDK. This works perfectly. However, if I try adding another key to my server side dictionary, return it to the app, and then try uploading the video, I will always receive an invalid signature response.

The extra key I am trying to add is `type` with a value of `private`. What's funny is on the iOS SDK if I choose to do an unsigned upload I can pass the `type` key with a value of `private` and the upload works fine, but I can never get it to work with the above code if I add the type `key` to the `dict`

How can I add additional params to the above code while still generating a valid signature?

**Comment by taragano** [comment]
Please make sure that you generate the signature based on an alphabetically-sorted set of parameters.
For more information:
http://cloudinary.com/documentation/upload_images#creating_api_authentication_signatures

**Comment by jingignoli** [comment]
Same thing when i want to add a context

**Comment by taragano** [comment]
Hi @jingignoli, 
I apologize for my response delay. 
If you still experience this issue, please share some snippets of your signature calculation code, and I'll be happy to assist.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
