### ISSUE TITLE
Incorrect link in blog post

### ISSUE THREAD

**Issue by holtkamp** [cloudinary/cloudinary_js#74]
In this [blog post](http://cloudinary.com/blog/how_to_automatically_create_images_for_responsive_design) a link is included to "[the Cloudinary JavaScript library](https://github.com/cloudinary/cloudinary_js/blob/master/js/jquery.cloudinary.js#L675)". 

Note that you guys linked to line 675 of the master branch, which by now has changed, thereby confusing the user.

You can use the 'y' key on your keyboard to get the current commit to prevent this, also see this documentation: 

https://help.github.com/articles/getting-permanent-links-to-files/

**Comment by tocker** [comment]
@holtkamp thanks! We'll check it.
