### ISSUE TITLE
Wrong link and dependency is missing in the bower setup 

### ISSUE THREAD

**Issue by lironsher** [cloudinary/cloudinary_js#75]
jquery.ui is not installed with the provided command.

Also it should be :
"bower_components/jquery-ui/ui/widget.js"
and not 
"bower_components/jquery.ui/ui/widget.js"

**Comment by tocker** [comment]
jquery-ui is a shim package provided by [components](https://github.com/components/components).
jquery.ui is the package maintained by jQuery (https://github.com/jquery/jquery-ui) - which is what we are using.
