### ISSUE TITLE
Undefined object rmargin

### ISSUE THREAD

**Issue by spark1989** [cloudinary/cloudinary_js#76]
Hello, an undefined object error (rmargin) is thrown after calling cloudinary_update() function. src is successfully generated from data-src prop, but then throws this error afterwards.

https://github.com/cloudinary/pkg-cloudinary-core/blob/master/cloudinary-core.js#L227

**Comment by kettuniko** [comment]
Still existing. Check line #147 https://github.com/cloudinary/pkg-cloudinary-core/blob/master/cloudinary-core.js#L147

**Comment by diegopamio** [comment]
Any solution to this please??
