### ISSUE TITLE
Element not catching 'cloudinarydone' trigger

### ISSUE THREAD

**Issue by twler** [cloudinary/cloudinary_js#77]
I have a file upload that sends the file just fine, but it isn't registering the trigger afterward:

    form
      .append($.cloudinary.unsigned_upload_tag 'cloudinary_transform', {
          cloud_name: 'mysite',
          tags: 'mytag'
        }).bind('cloudinarydone', () -> console.log 'finished')

I have also tried variations of

    form
      .append($.cloudinary.unsigned_upload_tag 'cloudinary_transform', {
          cloud_name: 'mysite',
          tags: 'mytag'
        }).on('cloudinarydone', () -> console.log 'finished')

The image uploads just fine, and I see the data response in the console, but I'm not able to register the trigger (i.e. `finished` is never logged).

Has this been changed recently, or is there some other obvious problem?

**Comment by nadavofi** [comment]
Your syntax is not well formed. Try the following:

```
$('body').append($.cloudinary.unsigned_upload_tag('cloudinary_transform', {
      cloud_name: 'mysite',
      tags: 'mytag'
    })).bind('cloudinarydone', function() {console.log("finished")});
```

**Comment by twler** [comment]
Thanks for your answer.  Sorry for not mentioning, but it is coffeescript and is equivalent to what you have written:

    form.append($.cloudinary.unsigned_upload_tag('cloudinary_transform', {
        cloud_name: 'mysite',
        tags: 'mytag'
    })).bind('cloudinarydone', function() {
        return console.log('finished');
    });

See [here](http://coffeescript.org/#try:form%0A%20%20.append(%24.cloudinary.unsigned_upload_tag%20'cloudinary_transform'%2C%20%7B%0A%20%20%20%20%20%20cloud_name%3A%20'mysite'%2C%0A%20%20%20%20%20%20tags%3A%20'mytag'%0A%20%20%20%20%7D).on('cloudinarydone'%2C%20()%20-%3E%20console.log%20'finished')) for reference

Any other ideas as to what could be the issue?

**Comment by TalLevAmi** [comment]
append will return the form and not the upload tag, so the binding is done on the wrong element. 
Try:
```
$.cloudinary.unsigned_upload_tag('cloudinary_transform', {
    cloud_name: 'mysite',
    tags: 'mytag'
}).appendTo(form).bind('cloudinarydone', function() {
    return console.log('finished');
});

```

**Comment by twler** [comment]
Great, this solved it for me -- thanks!

Solution below (with function inputs) for future reference by others:

    $.cloudinary.unsigned_upload_tag('cloudinary_transform', {
        cloud_name: 'mysite',
        tags: 'mytag'
    }).appendTo(form).bind('cloudinarydone', function(e, data) {
        return console.log('finished', e, data);
    });
