### ISSUE TITLE
Cloudinary clobbering lodash

### ISSUE THREAD

**Issue by mikepc** [cloudinary/cloudinary_js#80]
Discovered my error. Shrinkwrap is not for me.

**Comment by mikepc** [comment]
Specifically _.startsWith _.endsWith _.contains are the most painful to lose.

**Comment by tocker** [comment]
Hi @mikepc,

Thanks for updating us!

[For anyone having a similar issue:]
The shrinkwrap version is specifically designed for developers who *do not* use lodash. If you are using lodash in your application, you should use the `cloudinary-core` package.
