### ISSUE TITLE
Signed Uploads: Any docs on the browser request that needs sent?

### ISSUE THREAD

**Issue by jimmiebtlr** [cloudinary/cloudinary_js#81]
Don't really want to use this library due to all the extra stuff it brings in. All that's really needed is given a file, what headers and such do I need to set.

Is there any documentation on the actual headers that need set for a signed upload?

**Comment by bkniffler** [comment]
I'd like to know too. Have you succeeded?

**Comment by jimmiebtlr** [comment]
Believe in term's of post request fields I sent

      public_id
      upload_preset
      api_key
      api_secret
      cloud_name
      resource_type

**Comment by taragano** [comment]
Following up @jimmiebtlr 's response, it's important to clarify a few pointers:

1. `resource_type` and `cloud_name` are both included in the URL itself, e.g.,:

        https://api.cloudinary.com/v1_1/<cloud name>/<resource_type>/upload
Therefore, these aren't passed as part of the upload parameters.
2. The `api_secret` should never be included as part of your request, and must be excluded from your client-side code. The `api_secret` should be stored securely on your server-side and should be used only for calculating the signature based on the upload parameters.
3. `upload_preset` is optional (for signed uploads).
4. `public_id` is also optional.
5. `timestamp` wasn't mentioned, but it is an obligatory parameter (for signed uploads).
6. `api_key` is necessary only for signed uploads.
7. There are lots of other parameters that you can pass as part of the upload request too, depending on your requirements, e.g., eager transformations, incoming transformations, and many others.

**Comment by jimmiebtlr** [comment]
Haven't worked with it in awhile, but that was specifically for the signature calculation passed to

**Comment by bkniffler** [comment]
Thanks for the input, I managed to succeed. First I calculate the signature on server side using
```
cloudinary.utils.sign_request({ timestamp: Math.round(new Date().getTime()/1000) });
// returns { signature, api_key, timestamp }
```
On the browser, I call this method through my API and attach the properties as fields like here (with superagent)
```
const request = superagent
        .post("https://api.cloudinary.com/v1_1/<cloud name>/auto/upload")
        .on('progress', ({ percent }) => console.log(`${percent}%`))
        .field('api_key', cloudinary.api_key)
        .field('signature', cloudinary.signature)
        .field('timestamp', cloudinary.timestamp);
```

And done!
