### ISSUE TITLE
can this be used with angular2?

### ISSUE THREAD

**Issue by yahyaKacem** [cloudinary/cloudinary_js#85]
Hi, can this be used with angular2 with typescript and browserify?
should I use the cloudinay-core or cloudinary-npm for an angular2 app?

**Comment by tocker** [comment]
You will need to create a definition file to use the Cloudinary library with TypeScript (just like any other plain javascript library).
The Cloudinary AngularJS does not support AngularJS 2 yet, but you can use cloudinary-core or cloudinary-jquery with AngularJS 2 apps.
