### ISSUE TITLE
cloudinary.api.resource does not work with videos

### ISSUE THREAD

**Issue by WelltokCaleb** [cloudinary/cloudinary_js#86]
I'm iterating through a collection of "media", which includes both images and video, and trying to get media details (resource_type, width, height, etc) using cloudinary.api.resource(id), but it fails to find videos.

**Comment by roeeba** [comment]
Iterating through Cloudinary resources can currently only be done separately for each `resource_type`. By default, if no `resource_type` is defined, a query of `image` type resources will be returned. In order to get a list of video resources please set `resource_type` to `video`.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
