### ISSUE TITLE
Is there any way to restrict the allowed image file types with jQuery.fn.cloudinary_fileupload?

### ISSUE THREAD

**Issue by timotgl** [cloudinary/cloudinary_js#87]
When using `$someInputField.cloudinary_fileupload()`, is there any way to pass an `options` object that restricts the allowed image file types (with MIME types ideally)? Passing something like `{allowed_formats: ['jpg']}` or `{allowed_formats: 'jpg,png'}` didn't work for me.

Is there documentation for the `options` accepted by https://github.com/cloudinary/cloudinary_js/blob/master/js/jquery.cloudinary.js#L3836 ?

**Comment by nadavofi** [comment]
Hi Timo,
I believe this should meet your requirements (on the client side):
https://github.com/cloudinary/cloudinary_js#client-side-image-resizing-before-upload
Note that you can do the same on the server-side (Cloudinary's server) using upload-preset. This will also allow you to [normalize non-allowed formats](https://support.cloudinary.com/hc/en-us/articles/205390662) into a specific format of your choice.

**Comment by waelbeso** [comment]
i get rid of this by Binding  the Attribute 'accept' with 'image/jpeg,image/gif,image/png'

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
