### ISSUE TITLE
Am I crazy or does the file upload field name HAVE to be "file"?

### ISSUE THREAD

**Issue by cannikin** [cloudinary/cloudinary_js#91]
Is there no way to signify a different name for the file upload field? What if you have multiple uploaders on the same page?

**Comment by taragano** [comment]
While the `name` should indeed be `file`, you can still have multiple upload fields on the same page.
For more information:
https://support.cloudinary.com/hc/en-us/articles/202519962-Can-I-have-multiple-upload-fields-on-the-same-page-

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
