### ISSUE TITLE
Bad request (400) error when posting directly to the API without jQuery

### ISSUE THREAD

**Issue by dace** [cloudinary/cloudinary_js#93]
Hi, 

Having an issue with posting directly to the Cloudinary upload API (without the use of jQuery as noted here in issue #38 and using this documentation [here](http://cloudinary.com/documentation/upload_images#uploading_with_a_direct_call_to_the_api)).

Using axios to make a post request like so with my uploaded file and unsigned_preset: 

```
// ...
// user uploaded image is being passed as props through the use of redux form

const cloudinaryURL = 'https://api.cloudinary.com/v1_1/<my_name_here>/image/upload';

axios.post(cloudinaryURL, {
      file: props,
      upload_preset: 'test123'
    })
    .then(function(response) {
      console.log(response)
    })
    .catch(function(error) {
      console.log(error)
    })
```

However, I keep getting a 400 bad request error:

`{"error":{"message":"Invalid file parameter. Make sure your file parameter does not include '[]'"}}`

Not sure if the issue is with my request (if I'm passing the file and unsigned_preset incorrectly) or if this is an issue with my file being passed. 

Thanks!

**Comment by hidace** [comment]
I decided to use the XMLHttpRequest, rather than Axios. Once redux props are appended to a new FormData(), it works:

```
// ...
// Synchronous example...

  const data = new FormData();
  data.append('file', props);
  data.append('upload_preset', uploadPreset);
  data.append('api_key', apiKey);

  const xhr = new XMLHttpRequest();
  xhr.open('POST', cloudinaryURL, false);
  xhr.send(data);
  const imageResponse = JSON.parse(xhr.responseText);
```

(Please checkout [my question/answer on stackoverflow re: XMLHttpRequest's responseText](http://stackoverflow.com/questions/38526994/xmlhttprequest-has-a-200-status-but-responsetext-is-empty/38527398#38527398) for the preferred async way to handle this.)

Thanks.

**Comment by FrenchMajesty** [comment]
I had the same issue. I also decided to use something else and it worked. What could be causing this problem? It seems like axios doesn't function well with cloudinary.

**Comment by eitanp461** [comment]
Here's a live example of using Axios to upload files directly to Cloudinary - https://codepen.io/eitanp461/pen/zzXEzb?editors=1010.

Don't forget to replace the credentials with your account's cloud name and unsigned upload preset. 

It is based on `FormData`. The gist of it is:

```
  var url = `https://api.cloudinary.com/v1_1/${cloudName}/upload`;
  var fd = new FormData();
  fd.append("upload_preset", unsignedUploadPreset);
  fd.append("tags", "browser_upload"); // Optional - add tag for image admin in Cloudinary
  fd.append("file", file);
  const config = {
    headers: { "X-Requested-With": "XMLHttpRequest" },
  };
  axios.post(url, fd, config)
     .then(function (res) {...})
     .catch(function (err) {...});
```

**Comment by thebucknerlife** [comment]
Does anyone know why Cloudinary won't accept requests made with `http fetch`? I've had this issue before, with fetch being so barebones there are often things that are commonly done by other libraries but not fetch. I was able to an `XMLHttpRequest` without incident. But would love to use fetch, like we're using elsewhere.

**Comment by eitanp461** [comment]
@thebucknerlife here's an example of using fetch - https://codepen.io/eitanp461/pen/NdPNmX

Don't forget to replace the credentials with your account's cloud name and unsigned upload preset.


The main function is the fetch `then` callback, called when the promise is resolved:

```
function progress(response) {
  var reader = response.body.getReader();
  var decoder = new TextDecoder();
  var decodedValue;
  
  function update() {
    return reader.read().then(function(result) {
      if (result.done) {
        // Return final response from Cloudinary to next handler
        return (JSON.parse(decodedValue));
      }
      decodedValue = decoder.decode(result.value || new Uint8Array, {
        stream: true
      });
      // Continue reading response
      return update();      
    });
  }
  return update();
}
```

Which is used by the `fetch` invocation:
```
  var fd = new FormData();
  fd.append('upload_preset', unsignedUploadPreset);
  fd.append('file', file);

  fetch(url, {
      method: 'POST',
      body: fd
    })
    .then(progress);
```

**Comment by emmanuelnwogbo** [comment]
> Here's a live example of using Axios to upload files directly to Cloudinary - https://codepen.io/eitanp461/pen/zzXEzb?editors=1010.
> 
> Don't forget to replace the credentials with your account's cloud name and unsigned upload preset.
> 
> It is based on `FormData`. The gist of it is:
> 
> ```
>   var url = `https://api.cloudinary.com/v1_1/${cloudName}/upload`;
>   var fd = new FormData();
>   fd.append("upload_preset", unsignedUploadPreset);
>   fd.append("tags", "browser_upload"); // Optional - add tag for image admin in Cloudinary
>   fd.append("file", file);
>   const config = {
>     headers: { "X-Requested-With": "XMLHttpRequest" },
>   };
>   axios.post(url, fd, config)
>      .then(function (res) {...})
>      .catch(function (err) {...});
> ```
Thank You. Cloudinary's documentation wasn't currently helpful in this regard. Do you have any links to the part of their documentation that discusses this?

**Comment by melitus** [comment]
I am still getting ```xhr.js:173 POST https://api.cloudinary.com/v1_1/melitus/image/upload 400 (Bad Request)```

**Comment by aleksandar-cloudinary** [comment]
Hi @melitus . I've had a look through our logs and the reason why you were getting this error was that there was no file provided for the upload. A few of the uploads also failed as there was no upload preset being specified. However, the last 3 upload logs are showing successful uploads with a provided file.

**Comment by melitus** [comment]
@aleksandar-cloudinary I have fixed it by changing the upload_preset from sign to unsigned mode.
Thanks a lot

**Comment by aleksandar-cloudinary** [comment]
@melitus Great, thanks for confirming that this is now working for you.

**Comment by Bintysaed** [comment]
when I`M trying to upload file in the  into cloudinary I`M getting  this Error 
xhr.js:155 POST https://api.cloudinary.com/v1_1/amina/raw/upload/ 400 (Bad Request)
index.js:1437 Error upload file Error: Request failed with status code 400

Any help  your kind

**Comment by victorli-cloudinary** [comment]
@Bintysaed Could you please share your code with us so we can better assist you? And include any details you'd like, so we can figure out how you are uploading your file and how to fix it.

**Comment by melitus** [comment]
Share your code so that we can help you debug what is causing the bad
request issue

**Comment by mauwia** [comment]
t cloudnaryUpload=async (photo)=>{
        let CLOUDINARY_URL = 'https://api.cloudinary.com/v1_1/dk8xi5rcy/upload';
        const data=new FormData()
        data.append('file',defaultAvatar)
        data.append('upload_preset','Bazzz1999')
        data.append("cloud_name",'dk8xi5rcy')
        try{
        const config = {
                headers: { "X-Requested-With": "XMLHttpRequest" },
              };
        let result=await Axios.post(CLOUDINARY_URL,data,config)
        console.log(result)
        }catch(err){
            console.log(err)
        }
    }
thts my code still not working

**Comment by victorli-cloudinary** [comment]
@mauwia I'm seeing some errors in our logs, some saying `Invalid URL for upload` and some saying `Unsupported source URL: 3`. Could you change `CLOUDINARY_URL` to `https://api.cloudinary.com/v1_1/dk8xi5rcy/image/upload` and double check the `defaultAvatar` that is being passed in is a valid image file, and see if the issue persists?

**Comment by mauwia** [comment]
Can u give me relevant code??

**Comment by Vdeub-cloudinary** [comment]
Hi @mauwia, your code is working properly. The issue here is that you are passing the string `"3"` as a file which will raise the `Unsupported source URL: 3`. You can find the file source options supported [here](https://cloudinary.com/documentation/upload_images#file_source_options). Could you share how you retrieve the file on your side? Normally, you should be able to get the file like this `file = input.files[0];` where input is the element where you upload the file.

**Comment by Vdeub-cloudinary** [comment]
Hi @mauwia, your code is working properly. The issue here is that you are passing the string `"3"` as a file which will raise the `Unsupported source URL: 3`. You can find the file source options supported [here](https://cloudinary.com/documentation/upload_images#file_source_options). Could you share how you retrieve the file on your side? Normally, you should be able to get the file like this `file = input.files[0];` where input is the element where you upload the file.

**Comment by Vdeub-cloudinary** [comment]
Hi @mauwia, your code is working properly. The issue here is that you are passing the string `"3"` as a file which will raise the `Unsupported source URL: 3`. You can find the file source options supported [here](https://cloudinary.com/documentation/upload_images#file_source_options). Could you share how you retrieve the file on your side? Normally, you should be able to get the file like this `file = input.files[0];` where input is the element where you upload the file.
