### ISSUE TITLE
How to upload images from multiple input element using NodeJS

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [cloudinary/cloudinary_js#96]
Hi, 
Actually i want to upload images from multiple input elements in a single form using cloudinary.

But am surfing for whole day i didn't find any documentation regarding this.

And also i need to upload images directly from browser using nodeJS 

Thanks in Advance

**Comment by taragano** [comment]
Hi @KalaiselvanMahendran,

Uploading directly from the browser with the NodeJS SDK is documented here:
http://cloudinary.com/documentation/node_image_upload#direct_uploading_from_the_browser

The following explains about having multiple input field on the same page:
https://support.cloudinary.com/hc/en-us/articles/202519962-Can-I-have-multiple-upload-fields-on-the-same-page-

**Comment by Haocen** [comment]
The document is rather unclear on certain parts.
For example:
```
var url = require('url');
var url_parts = url.parse(request.url, true);
var query = url_parts.query;

var preloaded_file = new cloudinary.PreloadedFile(query.image_id);
if (preloaded_file.is_valid()) {
  photo.image_id = preloaded_file.identifier();
} else {
  throw("Invalid upload signature");
}
```
Where should this piece of code be? is `image_id` the actual id of an input element on my page?
I tried to implement direct browser upload with generated input HTML element from node js but after selecting file nothing happen afterwards.

**Comment by taragano** [comment]
The `image_id` will be used in the `name` of the hidden field that's created automatically after the upload, that's field `value` will be assigned with the identifier of the uploaded file.
Please see our [sample project](https://github.com/cloudinary/cloudinary_npm/tree/master/samples/photo_album) for usage reference.

Specifically, see:
https://github.com/cloudinary/cloudinary_npm/blob/master/samples/photo_album/views/photos/add_direct.ejs#L19

and:
https://github.com/cloudinary/cloudinary_npm/blob/b101e3bda667dac307c08bca3084538921f45fec/samples/photo_album/controllers/photos_controller.js#L119-L150

**Comment by Haocen** [comment]
Thank you very much, I get it working.
The client side JavaScript snippet is not even mentioned in your doc, would appreciate if you can do some update and clean up.

**Comment by taragano** [comment]
Thank you for the update @Haocen, I'm glad it's working for you now :)
Also, we appreciate your feedback, we'll do our best to make this clearer in our docs.
Please let us know if there's anything else we can help you with.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
