### ISSUE TITLE
upload video error

### ISSUE THREAD

**Issue by rainweb** [cloudinary/cloudinary_js#97]
Upload failed: Invalid value jpg for parameter video_file_type
{ 
                        cloud_name: 'klook',
                        folder:"admin",
                        multiple: false,
                        upload_preset: '*****',
                        sources: ['local'],
                        resource_type: 'video'
                    }

**Comment by MaorGariv** [comment]
Hi,

The error is probably because you're trying to upload **videos** but in your upload preset there is a `format` request for `jpg` (i.e., trying to convert videos to `jpg`). Try to change the `format` values to be compatible for videos.

**Comment by rainweb** [comment]
@MaorGariv thks，fixed
