### ISSUE TITLE
How to deal with iFrame

### ISSUE THREAD

**Issue by NitroBAY** [cloudinary/cloudinary_js#99]
`$.cloudinary.responsive()` doesn't work because my images must be inside an iframe (tinymce), I can do something like `$('iframe').contents().find('.dynamic-image').last().cloudinary()` but then it's not responsive ?
PS : I know iFrame sucks but it's tinymce's fault.

**Comment by NitroBAY** [comment]
The full story is that I have an editor (WYSIWYG) which is an iFrame. When I insert images it goes directly to the iFrame. This is just a way to edit texts, it could be either an admin or an user who edit the text, if it was only admin I could give an horrible static image not responsive but users also edit texts.
So when an image is inserted into an iFrame it HAS to be be responsive. I already waste full days on Cloudinary, including because when one calls unsigned_cloudinary_upload() on a node, it's stupid but  <input> has to have name="file" tough it's not mentioned in articles

**Comment by tocker** [comment]
Hi @NitroBAY,
If the iframe src on the same domain as your main document?
Can you load scripts on the iframe?

**Comment by NitroBAY** [comment]
The iFrame is generated by a plugin on the DOM so it is on the same domain that the website. I'll check if tinyMCE (the WYSIWYG editor) allow me to load script when it generated an iFrame, thanks.

**Comment by tocker** [comment]
Good luck!

Here's a little script to help you test. Note that using requirejs, webpack, browserify et al will probably be better for production use.

```javascript
var f;
var createIFrame = true;
if (createIFrame) {
// create a frame and append it to the current page
    f = document.createElement('iframe');
    f.setAttribute('width', '50%');
    f.setAttribute('height', '100%');

    document.body.appendChild(f);
} else {
// ~~or~~

// get the frame created by the plugin
    f = document.getElementById('frame_id');
}

// create a script tag on iframe
// onload is used to make sure each script is loaded before loading the next one
var scriptTag = f.contentDocument.createElement('script');
scriptTag.innerHTML =
        "function loadScript(src, onload) {" +
        "    var tag = document.createElement('script');" +
        "    tag.src = src;" +
        "    if( onload) { tag.onload = onload;}" +
        "    document.head.appendChild(tag);" +
        "}" +
        "loadScript('https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js', function(){" +
        "    loadScript('https://cdnjs.cloudflare.com/ajax/libs/cloudinary-jquery-file-upload/2.1.2/cloudinary-jquery-file-upload.min.js', function(){" +
        "        window.cl = cloudinary.Cloudinary.new({cloud_name: 'demo', responsive: true});" + "" +
        "        document.body.append(cl.image('sample', {width: 'auto', crop: 'scale'}));" +
        "        cl.responsive()" +
        "    })" +
        "});";
f.contentDocument.body.appendChild(scriptTag);

```

**Comment by NitroBAY** [comment]
Due to very very particular structure of tinymce iframe and Meteor (the isomorphic framework I use) it would be simpler if cloudinary could take as a possible option the iframe one wants to work on.

**Comment by NitroBAY** [comment]
```
        ed.on('init', () => {
          $('script').each((i, script) => {
            $(ed.getWin().document.body).append($(script));
          });

          const script = ed.getWin().document.createElement('script');
          script.src = '/iframeImage.js';
          ed.getWin().document.body.appendChild(script);
        });
      }
```

**Comment by NitroBAY** [comment]
No finally Meteor is special so <script> are useless without Meteor's way of do it, but I have a function in my iFrame which takes the cl instance `function responsive(myCloudinary)`. Now with the lack of doc on the js version I still need to figure out how `<img data-src="">` -> `<img src="w_(basedonwidth)'>`

**Comment by NitroBAY** [comment]
@tocker could you also explain responsive() ?

**Comment by NitroBAY** [comment]
I just want a responsive image 
`    const url = myCloudinary.url(data.result.public_id, { client_hints: true, crop: 'scale',
      width: 'auto', dpr: 'auto', responsive_placeholder: 'blank',
      quality: 80, format: 'jpg', fetch_format: 'auto' });`
it gives this URL http://res.cloudinary.com/****SECRET****/image/upload/c_scale,dpr_auto,f_auto,q_80,w_auto/out2lgy2gbqzza8goek9.jpg with the class cld-responsive
It loads an huge 4K image which is not great 
After the img is inserted I try to do (getWin() gives the windows of iFrame). 
`editor.getWin().responsive(myCloudinary);` 

```
function responsive(myCloudinary) {
  myCloudinary.cloudinary_update(document.getElementsByTagName('img'));
}
```
BUT the URL is still http://res.cloudinary.com/dnr98e5qo/image/upload/c_scale,dpr_auto,f_auto,q_80,w_auto/out2lgy2gbqzza8goek9.jpg

**Comment by NitroBAY** [comment]
Finally due to the non compatibility between Meteor and iFrame, cloudinary has to change to have an option iFrame.

**Comment by NitroBAY** [comment]
I lost more than a full month with cloudinary, so I really seek for a short answer to my problem now.

**Comment by taragano** [comment]
Sorry for our response delay @NitroBAY.
Note that when using responsive functionality the url should be placed in `data-src` and not in `src`. A url placed in `src` will be immediately loaded by the  browser, before the responsive script has changed `w_auto` to the appropriate value.

**Comment by NitroBAY** [comment]
Yes I know

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
